### ISSUE TITLE
Support for Index Lifecycle Management API

### ISSUE THREAD

**Issue by thinkspill** [elastic/elasticsearch-php#1008]
As of v7.6.1, I couldn't find support for creating/managing ILM policies within the client.

Is this currently supported and I missed it, or is it on the road map?

Thanks!

**Comment by ezimuel** [comment]
The ILM APIs are part of the [X-Pack](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-xpack.html) endpoints. In the past we managed this in a separate repository [elastic/elasticsearch-x-pack-php](https://github.com/elastic/elasticsearch-x-pack-php). Unfortunately, this repository is not updated since ES 5.x. I'm working to update it in order to release a version for ES 6.x.

For 7.x I would like to dismiss this repository and merge the XPack endpoints into [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) directly. I'll try to merge it for the next minor version elasticsearch-php 7.7.

**Comment by ezimuel** [comment]
@thinkspill I created the `7.7` branch to support the upcoming Elasticsearch 7.7. This new release contains also the XPack endpoints. You can test it using the following composer command:
```bash
composer require elasticsearch/elasticsearch:7.7.x-dev
```

**Comment by ezimuel** [comment]
@thinkspill I released [elaticsearch-php 7.7.0](https://github.com/elastic/elasticsearch-php/releases/tag/v7.7.0) that includes all the XPack endpoints. Now you can creating/managing ILM policies.
