### ISSUE TITLE
Any thoughts about async client implementation

### ISSUE THREAD

**Issue by ndobromirov** [elastic/elasticsearch-php#102]
In the recent days I've been interested in the ReactPHP project and everything around it.

Can you give me some feedback on whether you see good reasons in an asynchronous, client implementation based on this https://github.com/reactphp/http-client.

BR,
Nikolay Dobromirov.

**Comment by mfn** [comment]
A gently ping to @polyfractal , to you think that due the work on 2.0 using https://github.com/guzzle/RingPHP , which supports asynchronicity, the following may not be true anymore:

>  The API of the library is sync by nature, so a changeover to async would require the whole library to become async as well

Thanks!

**Comment by polyfractal** [comment]
@mfn Yep, I'll eat my hat on that statement :)

The work that @mtdowling has done on RingPHP has made it very easy to expose async behavior.  The changeover still required a complete retooling of the internal core, but wasn't too difficult to "hide" inside the API facade and only expose if the user wanted it.

I still don't know much about React personally, but since 2.0 can return futures (because RingPHP uses React promises under the hood) instead of explicit responses, I imagine it would play much nicer with React than the 1.0 branch.

**Comment by polyfractal** [comment]
Closing, since `v2.0.0` is based on RingPHP and now offers a "future mode" which exposes React promises :)
