### ISSUE TITLE
The travis setup looks broken

### ISSUE THREAD

**Issue by stof** [elastic/elasticsearch-php#103]
The repo contains a config file for Travis, but the last build on Travis was 5 months ago: https://travis-ci.org/elasticsearch/elasticsearch-php/builds
It looks like the hook triggering builds is missing

**Comment by TomasVotruba** [comment]
@polyfractal Looks like almost year passed and CI is here.

I can take care of Travis (got many issues at from the start, so I understand your attitude).
Since there are unit tests and that's all I need to make it run.

**Comment by polyfractal** [comment]
Thanks for the poke.  We opened Jenkins a while ago but I completely forgot to make note of it here.

Our CI summary page:  http://build.elastic.co/
ES-PHP 1.0: http://build-eu-00.elastic.co/job/es-php_core_10/
ES-PHP Master: http://build-eu-00.elasticsearch.org/view/Clients/job/es-php_core/
ES-PHP Integration (currently unstable due to a jenkins issue): http://build-eu-00.elasticsearch.org/view/Clients/job/es-php_integration/

I'll add build badges to the README soon.

I stand by my statement from before:  I'm disinclined to invest energy in Travis since we already have a (relatively) robust CI setup.  It certainly isn't without it's faults, but considering the complexity testing all the various versions, Travis is still going to be a pain.

**Comment by stof** [comment]
@polyfractal maybe Travis could be kept with testing against a single ES version (the one preinstalled on Travis, to simplify the setup), which would allow to have tests running on PRs for a faster feedback loop rather than having tests running only after a merge. Having tests against a single version of ES for pending PRs is still better than no tests running at all

**Comment by polyfractal** [comment]
@stof Hmm, yeah, that seems fair.  It would provide a simple litmus test if the PR is completely broken or not.  And it would be less work for Travis too, I would feel a little bad about running the full matrix on their infrastructure.

Might as well give it a shot...worst case we can just disable Travis again if it proves too much hassle, or not helpful enough.  I'll lodge another request with our infra team to investigate Jenkins-PR plugins...I think that request was lost in an internal overhaul of the jenkins system.

:+1: from me for a smaller version of Travis running :)

**Comment by TomasVotruba** [comment]
@polyfractal  Great job! :+1: 

Let me handle any hassles you came across.

**Comment by polyfractal** [comment]
Closing, travis support was added a few weeks ago.

(currently broken, but a totally different problem.  Will fix that soon!)
