### ISSUE TITLE
ES 7.6.2 is missing

### ISSUE THREAD

**Issue by truls1502** [elastic/elasticsearch-php#1049]
### Summary of problem or feature request

I am using [Elasticsearch 7.6.2](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/release-notes-7.6.2.html)

### Suggestion?
- Could you create a new release tag? Or at the moment I am using a workaround such as: ` "elasticsearch/elasticsearch": "7.6.2 as 7.6.1"` which works, but would be nice to have own version if it is possible 🤓 

Or maybe you had a reason to skip this version?

**Comment by ezimuel** [comment]
@truls1502 if you mean that `elasticsearch-php` does not have a `v7.6.2` release this is because we don't update it on each patch release of Elasticsearch (ES). The [7.6.1](https://github.com/elastic/elasticsearch-php/releases/tag/v7.6.1) version of elasticsearch-php is compatible with all the ES `7.6.x` versions. We only update `elasticsearch-php` for minor and major releases of ES.

**Comment by ezimuel** [comment]
@truls1502 I'm closing this issue. If you need more information I'll reopen it. Thanks.
