### ISSUE TITLE
Elasticsearch\Endpoints\Indices\ExistsIndexTemplate::getURI returns invalid URI

### ISSUE THREAD

**Issue by adamwojs** [elastic/elasticsearch-php#1072]
Hi! 

### Summary of problem or feature request

Valid `Elasticsearch\Namespaces\IndicesNamespace::existsIndexTemplate` method call (see snippet below) throws  `Elasticsearch\Common\Exceptions\BadRequest400Exception: Unknown 405 error from Elasticsearch null` exception instead of return boolean value. 

The cause of the issue is invalid URI generated by [`\Elasticsearch\Endpoints\Indices\ExistsIndexTemplate::getURI`](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Indices/ExistsIndexTemplate.php#L38). For a given example it returns  `/_index_template/foo` is instead of  `/_template/foo` (base on https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-template-exists.html).  

### Code snippet of problem

```php
/** @var \Elasticsearch\Client $client */ 
$client->indices()->existsIndexTemplate(['name' => 'foo'])
```

### System details

- Operating System: GNU/Linux x86_64
- PHP Version: PHP 7.4.8
- ES-PHP client version: 7.9 
- Elasticsearch version: 7.9

**Comment by ezimuel** [comment]
The `/_index_template/{name}` is an **experimental** API introduced in Elasticsearch 7.8, see the API specification [here](https://github.com/elastic/elasticsearch/blob/v7.8.0/rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists_index_template.json). This API has been introduced to play with the next Elasticsearch API (v2).

I double check using Elasticsearch 7.9 and elasticsearch-php 7.9 and this API works fine. The result is a boolean, as follows:
```php
require 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()->build();

$response = $client->indices()->existsIndexTemplate(['name' => 'foo']);
var_dump($response); // false
```
If you have a snippet of code that reproduces the issue please share here.

The API URL that you suggested `/_template/foo` is part of the `indices()->existsTemplate(['name' => 'foo'])`. This is a stable API that has been around for many years. The documentation is the one that you pointed out, [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-template-exists.html). 
I suggest to use it instead of `existsIndexTemplate`.
