### ISSUE TITLE
[Question] Does this package offer performance improvement over Guzzle?

### ISSUE THREAD

**Issue by antoniovj1** [elastic/elasticsearch-php#1194]
First of all, if this is not the proper place to ask a question I'll remove the issue ASAP.

I'm currently using elastic search for a high throughput app. I generate the query and I run it directly using Guzzle the I parse the response etc.

I'd like to know if this package in addition to ease the queries adds some performance improvements. Thanks

**Comment by ezimuel** [comment]
@antoniovj1 this library offers all the Elasticsearch APIs (i.e. about 400 endpoints) as functions and manages the [connection pool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/connection_pool.html), you can specify a set of hosts and the library will route the requests to all the host (eg. using a [RoundRobin](https://www.elastic.co/guide/en/elasticsearch/client/php-api/7.16/selectors.html#_roundrobinselector_default) selector).

The `7.x` version uses a fork of [ringphp](https://github.com/ezimuel/ringphp) that is a library based on Guzzle. The new 8.x version will use any [PSR-18](https://www.php-fig.org/psr/psr-18/) client. This means you can choose the HTTP library that you want: Guzzle, Symfony HTTP, etc (here a [full list of PSR-18 HTTP client](https://packagist.org/providers/psr/http-client-implementation)). You can have a look at my [last presentation](https://www.zimuel.it/talks/PHPJapan2021.pdf) about `elasticsearch-php` for more information.

Regarding your question about perfomance, I would say that 7.x doesn't offer improvement on the HTTP transport (since it's basic Guzzle) but it improves the overall performance since it's implement connection pool and facilitate the HTTP request-and-retry mechanism.

**Comment by antoniovj1** [comment]
@ezimuel Thank you very much for the information
