### ISSUE TITLE
NoAliveException not moved to new namespace

### ISSUE THREAD

**Issue by panvid** [elastic/elasticsearch-php#1209]
The new major version 8.0.0 provides a new Namespace for Eceptions: `Elastic\ElasticSearch\Exception`.

I found an Exception, which is missed move to the new namespace in `Incides`-Endpoint: https://github.com/elastic/elasticsearch-php/blob/8.0/src/Endpoints/Indices.php#L23

```php
use Elastic\Transport\Exception\NoAliveException;
```

**Comment by ezimuel** [comment]
@panvid thanks for reporting the issue. It's a typo since it should be [NoNodeAvailableException](https://github.com/elastic/elastic-transport-php/blob/master/src/Exception/NoNodeAvailableException.php). This is an exception of [elastic/elastic-transport-php](https://github.com/elastic/elastic-transport-php) so it's ok to have it under `Elastic\Transport\Exception`. Since this is a generated code I need to fix the code generator and I'll release a `8.0.1` soon.
