### ISSUE TITLE
The array structure of a batch index is confusing

### ISSUE THREAD

**Issue by RORUI** [elastic/elasticsearch-php#1261]
That's what the official document says:
**Bulk indexing with PHP arrays.**
```
for($i = 0; $i < 100; $i++) {
    $params['body'][] = [
        'index' => [
            '_index' => 'my_index',
	    ]
    ];

    $params['body'][] = [
        'my_field'     => 'my_value',
        'second_field' => 'some more values'
    ];
}

$responses = $client->bulk($params);
```
The above array structure is confusing, so why not do it:
```
for($i = 0; $i < 100; $i++) {
    $params[] = [
        'index' => [
            '_index' => 'my_index',
            '_id' => $i
	    ],
       'body' => [
        'my_field'     => 'my_value',
        'second_field' => 'some more values'
       ]
    ];
}

$responses = $client->bulk($params);
```

- Operating System win10
- PHP Version 8
- ES-PHP client version lasted
- Elasticsearch version 8

**Comment by ezimuel** [comment]
@rory5515 you cannot use your solution since we need to create an array of operations in the `body` field. Each operations has two rows, the first is the operation type (e.g. `index`) and the second is the document data. If you see the HTTP Bulk API specification [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html), you can see why we needed to do that.
Let me know if you need more help, thanks.

**Comment by murilolivorato** [comment]
the same question
