### ISSUE TITLE
Documentation Update Request - Scan and Scroll

### ISSUE THREAD

**Issue by FabienO** [elastic/elasticsearch-php#138]
Hey there, 

Sorry if this is the wrong place but I can't find a forum or an email or anywhere to get in contact. I would really like if we had some more documentation on how to use scan and scroll with this library. I see there's code in there to support the feature but can't seem to configure it correctly to use it. If this is the wrong place to ask please close/delete the issue and let me know where I can ask this kind of question. 

Kind regards,
Fab

**Comment by reafle** [comment]
Is order of params important?

Because this
```php
$query = array(
    "search_type" => "scan",
    "scroll" => "30s"
);
$client = new Elasticsearch\Client();
$client->search($query);
```
seems to respond with 500 and `ElasticsearchException[Scroll must be provided when scanning...]`, 
but this
```php
$query = array(
    "scroll" => "30s",
    "search_type" => "scan"
);
$client = new Elasticsearch\Client();
$client->search($query);
```

seems to work just fine.

**Comment by polyfractal** [comment]
Parameter order should be unimportant (the client doesn't care, and ES shouldn't either).

What version of Elasticsearch are you using?  On 1.6 it works fine for me:

```php
$query = array(
    "search_type" => "scan",
    "scroll" => "30s"
);
$client = new Elasticsearch\Client();
$results = $client->search($query);

print_r($results);


$query = array(
    "scroll" => "30s",
    "search_type" => "scan"
);
$client = new Elasticsearch\Client();
$results = $client->search($query);

print_r($results);
```
```php
Array
(
    [_scroll_id] => c2Nhbjs1OzE2Om9xQmt2YkNCUll1amtMWWdoQUdxN0E7MTc6b3FCa3ZiQ0JSWXVqa0xZZ2hBR3E3QTsxODpvcUJrdmJDQlJZdWprTFlnaEFHcTdBOzE5Om9xQmt2YkNCUll1amtMWWdoQUdxN0E7MjA6b3FCa3ZiQ0JSWXVqa0xZZ2hBR3E3QTsxO3RvdGFsX2hpdHM6Mjs=
    [took] => 1
    [timed_out] => 
    [_shards] => Array
        (
            [total] => 10
            [successful] => 5
            [failed] => 0
        )
    [hits] => Array
        (
            [total] => 2
            [max_score] => 0
            [hits] => Array
                (
                )
        )
)
Array
(
    [_scroll_id] => c2Nhbjs1OzIxOm9xQmt2YkNCUll1amtMWWdoQUdxN0E7MjI6b3FCa3ZiQ0JSWXVqa0xZZ2hBR3E3QTsyMzpvcUJrdmJDQlJZdWprTFlnaEFHcTdBOzI0Om9xQmt2YkNCUll1amtMWWdoQUdxN0E7MjU6b3FCa3ZiQ0JSWXVqa0xZZ2hBR3E3QTsxO3RvdGFsX2hpdHM6Mjs=
    [took] => 1
    [timed_out] => 
    [_shards] => Array
        (
            [total] => 10
            [successful] => 5
            [failed] => 0
        )

    [hits] => Array
        (
            [total] => 2
            [max_score] => 0
            [hits] => Array
                (
                )
        )
)
```

**Comment by reafle** [comment]
It's really weird. 

I'm using ES 1.7.0

Just tried it with `curl`, same thing:
```bash
curl -XPOST http://localhost:9200/_search?search_type=scan&scroll=1m
```
```json
{"error":"SearchPhaseExecutionException[Failed to execute phase [init_scan], all shards failed; shardFailures {[hDv-lh4aTpGQxivwtAI-jA][{index}][0]: ElasticsearchException[Scroll must be provided when scanning...]}{[hDv-lh4aTpGQxivwtAI-jA][{index}][1]: ElasticsearchException[Scroll must be provided when scanning...]}{[hDv-lh4aTpGQxivwtAI-jA][{index}][2]: ElasticsearchException[Scroll must be provided when scanning...]}{[hDv-lh4aTpGQxivwtAI-jA][{index}][3]: ElasticsearchException[Scroll must be provided when scanning...]}{[hDv-lh4aTpGQxivwtAI-jA][{index}][4]: ElasticsearchException[Scroll must be provided when scanning...]}]","status":500}
```
But:

```bash
curl -XPOST http://localhost:9200/_search?scroll=1m&search_type=scan
```
```json
{"_scroll_id":"cXVlcnlUaGVuRmV0Y2g7NTszNDY6aER2LWxoNGFUcEdReGl2d3RBSS1qQTszNDc6aER2LWxoNGFUcEdReGl2d3RBSS1qQTszNDg6aER2LWxoNGFUcEdReGl2d3RBSS1qQTszNDk6aER2LWxoNGFUcEdReGl2d3RBSS1qQTszNTA6aER2LWxoNGFUcEdReGl2d3RBSS1qQTswOw==","took":6,"timed_out":false,"_shards":{"total":10,"successful":5,"failed":0},"hits":{ .... } }
```

Do you have any ideas what can be wrong here?

**Comment by pickypg** [comment]
@reafle You need to put the URL in quotes. Your shell is seeing the `&` and truncating the rest of the URL.

```bash
curl -XPOST 'http://localhost:9200/_search?search_type=scan&scroll=1m'
```

**Comment by reafle** [comment]
Cool! 

That fixes the shell, but the php lib still has the problem :)

When I test it in the REST client, it works like a charm disregard of order.

**Comment by polyfractal** [comment]
Hm.  Well I don't *think* it is the client code, since I rely on [PHP to build the query params](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Connections/GuzzleConnection.php#L135), and after that it's up to libcurl to use it appropriately.

- The code that you initially attached, does that give you the failure or is there more code not being shown?  Just want to make sure there isn't something else that I'm missing in my reproduction test case.
- Can you attach a dump of `phpinfo()` so we can see what version of PHP and libcurl you are using?  I've encountered esoteric bugs with old versions libcurl in the past, so that's possible.
- What version of ES-PHP are you using?  Was it installed via composer or manually?
- Is the client being redirected through a proxy that could be interfering with URLs?
- Can you add this debug line after one of your failed attempts and then paste the output?

```php
print_r($client->transport->getLastConnection()->getLastRequestInfo());
```

**Comment by reafle** [comment]
Just reproduced it on another PC.

Seems like the problem is either with libcurl or with Guzzle, that was as far as I could trace it. 
Also, the script works well when run from CLI, but throws an error in the browser.
Now, to answer your questions:

* Yes, we reproduced it with a fresh composer install of `elasticsearch-php` (v1.3 and v1.4.3)
* ...how do i dump `phpinfo()`... https://jsfiddle.net/hT9vP/64/embedded/result/
* see poing 1
* no, there seems to be nothing in the way of directly hitting ES
* it dies with a fatal error - wrapping it with a try/catch gives this: https://gist.github.com/reafle/a386a1ee2b708792c38e

**Comment by polyfractal** [comment]
Thanks for the info.  Hmm...  I'm digging into change logs and bug reports (and spelunking through guzzle code).   Trying to hunt down why that ampersand is obtaining an extra urlencoded semi-colon (`;`).

```
[url] => http://%ip%:9200/_search?search_type=scan&%3Bscroll=30s
```

It's definitely happening sometime after the client, since that debug info is saved just immediately prior to handing it over to guzzle.

Can you gist up the `getLastRequestInfo()` debug output when the parameters are switched and it works correctly?  I'm curious if the ampersand/semicolon thing is happening there too.

To rule out Guzzle, can you try the other connection class?

```php
$params['connectionClass'] = '\Elasticsearch\Connections\CurlMultiConnection';
$client = new Elasticsearch\Client($params);
```

**Comment by reafle** [comment]
Oh, sorry to put you through this hassle. I myself had a long day with these issues :) maybe we should already move this to a separate issue?

You're right about the ampersand. Now that I try it with different params, I see it's always appended, only the first one works.

I was playing with parameters now, and any other params seems to break it, e.g.:

```php
$query = array(
    "size" => 1,
    "scroll" => "30s",
    "search_type" => "scan",
);
```

`getLastRequestInfo()` says
```php
[url] => http://127.0.0.1:9200/_search?size=1&%3Bscroll=30s&%3Bsearch_type=scan
```


If i switch the connection class, 

`getLastRequestInfo()` says
```php
[url] => http://127.0.0.1:9200/_search?size=1&scroll=30s&search_type=scan
```

BUT [the request is still handled incorrectly](https://gist.github.com/reafle/ad7da9a29d5361bc3e48 ), as you can see from the Response body - it completely ignored that I asked for a `_scroll_id`, only `size` parameter was processed.

Everything I try to trace leads me to libcurl calls, like
`/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:238`
`while (($mrc = curl_multi_exec($this->multiHandle, $active)) == CURLM_CALL_MULTI_PERFORM);`

or 

`/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/CurlMultiConnection.php:176`
`$execrun = curl_multi_exec($this->multiHandle, $running);`

And I don't really have a burning thirst to dig deeper into curl :)

I guess the question here is, why is it processed differently in apache, than in console? 

The other machine we tried it on had `curl v7.43`, which is pretty hip and new...

**Comment by polyfractal** [comment]
Curious indeed.  Do you have the ability to run these scripts from a shell version of php instead of Apache, just to confirm this is an Apache-related problem?  E.g. `$ php mySearchScript.php` ?

I see mod_rewrite in your phpinfo, do you have any rewrite or htaccess rules?  Rewriting should really only affect inbound requests to Apache (not outbound curl) if I understand it correctly, but perhaps you have a local domain setup (or `/etc/hosts`) so that local connections are actually going through apache and being rewritten before hitting ES?  I also see a redirect $_SERVER variable, maybe something funky is happening where the script is redirecting output to itself before hitting ES?

I'm not much of an Apache expert, unfortunately.  Sorta grasping at straws now... :(

Kitchen-sink questions now:

- Any firewalls or iptables that might be interfering/truncating the query strings?

- Can you try a basic curl example to see if it also explodes?

```php
$ch = curl_init();  
 
curl_setopt($ch,CURLOPT_URL, "http://127.0.0.1:9200/_search?size=1&scroll=30s&search_type=scan");
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
$response = curl_exec($ch);

curl_close($ch);
print_r($response);
```

- Can you verify there is only one ES node running locally?
- Can you try the CurlMultiConnection example and specify a type at the same time (e.g. http://127.0.0.1:9200/state/_search?size=1&search_type=scan&scroll=30s)
- Have you tried `localhost` instead of `127.0.0.1` (really long shot, but loopbacks get wonky from time to time, at least on my mac)

**Comment by reafle** [comment]
Hey, just to let you know.

We figured out the problem, it was our own fault.

there was a
```  
php_value arg_separator.output &amp;
```

set in the apache config, and it added that ampersand.

Thanks for the friendly support and helpful ideas though!

**Comment by polyfractal** [comment]
Hooray!  Glad you figured it out...I was starting to run out of ideas :)

Happy to help, feel free to open more tickets if you have questions/problems

**Comment by vrkansagara** [comment]
`"search_type" => "dfs_query_then_fetch",` solved my problem on php5.6
