### ISSUE TITLE
Sorting by nested field, using the sort parameter.

### ISSUE THREAD

**Issue by hanneskaeufler** [elastic/elasticsearch-php#179]
Hi there!

The client allows us to sort a result based on the param passed to the search method. E.g.

``` php
$params['index'] = 'myindex';
$params['sort'] = 'title';

$client->search($params);
```

Which translates to a URI search as described here: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-uri-request.html

Since issue https://github.com/elasticsearch/elasticsearch-php/issues/34 has been closed, we can also do things like:

``` php
// use the nested syntax
$params['sort']['title'] = ['order' => 'desc'];

$client->search($params);
```

Which is also translated to the same URI search syntax for Elasticsearch. However, it seems to me that nested sort queries are not supported like that? At least I can not get my query with a sort like this to work:

``` php
$params['sort'] = ['myField.sort' => ['order' => 'desc']];
```

where `myField.sort` results from a mapping where `.sort` is a multi field.
Compared to the above 

``` php
$params['sort'] = 'myField.sort:desc';
```

works as expected, but I cannot add the `ignore_unmapped: true` value :(

Any help would be appreciated!

**Comment by polyfractal** [comment]
Hmm, looking back, I think my fix was incorrect.  It was a generic fix since it affected multiple parameters (`post_filter`, etc), but it is doing the wrong thing for `sort`

The top-level `sort` parameter corresponds to the URI sort parameter, which does not accept `order` as part of its syntax.  The syntax is:

`/_search?sort=field1:asc,field2:desc`

So the PHP equivalent should be:

```php
$params['sort'] = [
  'field1' => 'asc',
  'field2' => 'desc'
]
```

E.g. an ordered hash that accepts field: sort_value.  The current ability to pass in arrays is broken, since it serializes the entire array as a urlencoded string (`/_search?sort[0][myField.sort][order]=desc`)...which is just wrong.

I'll put together some tests and fix this up.  Thanks for bringing this to my attention.

That said, you can't use `ignore_unmapped` in a URI sort values anyway.  You can only specify that as part of a sort value in the body:

```php
$params = [
    'index' => 'test_sort',
    'type' => 'test',
    'body' => [
        'sort' => [
            [
                'myField.sort' => [
                    'order' => 'desc',
                    'ignore_unmapped' => true
                ]
            ]
        ]
    ]
];
$response = $client->search($params);
```

I'll also update the docs when I patch the URI sort parameter, since it should be more clear which method to choose based on functionality needed.

**Comment by hanneskaeufler** [comment]
Hi, thanks. Yeah specifying the sort in the body works. It was just unclear to me, I thought the php client automagically appended the sort to the body when I specify "complex" sort params. Which it doesnt  do of course, but as you say it serializes the entire array as urlencoded string which doesnt work and fails silently.

**Comment by polyfractal** [comment]
No problem, definitely was confusing...I had to poke through the code and debugger for quite some time to realize what it was doing.  

I'm about to hop on a flight, but I'll try to get this fixed up and documented better soon.  Thanks again!

**Comment by polyfractal** [comment]
Closing due to age.
