### ISSUE TITLE
Uncaught Exceptions in GuzzleConnection.php

### ISSUE THREAD

**Issue by JugalSA** [elastic/elasticsearch-php#195]
Hello, 10 minute before my code was working fine and i was able to fetch all the data from ElasticSearch.
Now this error is very frustrating and worst part is i even don't know why?
Here is my code snippet:

```php
$es = new Elasticsearch\Client([
 			'hosts' => ['localhost:9200']
 		]);
$query = $es->search([
 				'body' => [
 					'query'=>[
 						'bool'=>[
 							'should '=>[
 								'match'=>['name' => "ponds"]
 							]
 						]
 					]
 				]
 		]);
```
Now its giving me this error.
Fatal error: Uncaught exception 'Guzzle\Http\Exception\ClientErrorResponseException' with message 'Client error response [status code] 400 [reason phrase] Bad Request [url] http://localhost:9200/_search' in D:\XamApp\htdocs\codeig\application\vendor\guzzle\guzzle\src\Guzzle\Http\Exception\BadResponseException.php:43 Stack trace: #0 D:\XamApp\htdocs\codeig\application\vendor\guzzle\guzzle\src\Guzzle\Http\Message\Request.php(145): Guzzle\Http\Exception\BadResponseException::factory(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Message\Response)) #1 [internal function]: Guzzle\Http\Message\Request::onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 D:\XamApp\htdocs\codeig\application\vendor\symfony\event-dispatcher\Symfony\Component\EventDispatcher\EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #3 D:\XamApp\htdocs\codeig\a in D:\XamApp\htdocs\codeig\application\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\GuzzleConnection.php on line 271

**Comment by polyfractal** [comment]
The `400` exception means there was a problem with your query syntax somehow.  The problem is an extra space in the `should` clause:

```php
'should '=>  [ ... ]
   //  ^---- Right here
```

If you remove that, your query should work.  If you run into these kinds of problems again in the future, you can catch the exception and then print out the ES error message:

```php
$es = new \Elasticsearch\Client([
    'hosts' => ['localhost:9200']
]);

try {
    $query = $es->search([
        'body' => [
            'query'=> [
                'bool'=> [
                    'should '=> [
                        'match'=>['name' => "ponds"]
                    ]
                ]
            ]
        ]
    ]);
} catch (\Exception $e) {
    // Print out the ES error message
    print_r($e->getMessage());
    
    // Print out the entire last request/response (including headers, body, curl info, etc)
    // This isn't used often and is mainly a debug tool
    print_r($es->transport->getLastConnection()->getLastRequestInfo());
}
```

Which would give you the JSON error.  ES exceptions are cryptic at best, so they may not be helpful, but sometimes can give you good info:

```json
{
   "error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[ishCGoUdQuKVUarCcdznIQ][test][0]: SearchParseException[[test][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"should \":{\"match\":{\"name\":\"ponds\"}}}}}]]]; nested: QueryParsingException[[test] [bool] query does not support [should ]]; }{[ishCGoUdQuKVUarCcdznIQ][test][1]: SearchParseException[[test][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"should \":{\"match\":{\"name\":\"ponds\"}}}}}]]]; nested: QueryParsingException[[test] [bool] query does not support [should ]]; }{[ishCGoUdQuKVUarCcdznIQ][test][2]: SearchParseException[[test][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"should \":{\"match\":{\"name\":\"ponds\"}}}}}]]]; nested: QueryParsingException[[test] [bool] query does not support [should ]]; }{[ishCGoUdQuKVUarCcdznIQ][test][3]: SearchParseException[[test][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"should \":{\"match\":{\"name\":\"ponds\"}}}}}]]]; nested: QueryParsingException[[test] [bool] query does not support [should ]]; }{[ishCGoUdQuKVUarCcdznIQ][test][4]: SearchParseException[[test][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"bool\":{\"should \":{\"match\":{\"name\":\"ponds\"}}}}}]]]; nested: QueryParsingException[[test] [bool] query does not support [should ]]; }]",
   "status":400
}
```

In particular, the part that says: `QueryParsingException[[test] [bool] query does not support [should ]]`.
Which would let you know that the problem is with the `should` clause in some capacity.

Hope this helps!  Let me know if you have any questions :)

**Comment by JugalSA** [comment]
Thank you so much..One more thing can you please share me some doc which has Elasticsearch query in php for applying more than one filters, range filter etc.
Once again thank you.

**Comment by polyfractal** [comment]
Use a `filtered` query + `bool` filter:

```php
$params = [
  'index' => 'my_index',
  'type' => 'my_type',
  'body' => [
    'query' => [
      'filtered' => [
        'filter' => [
          'bool' => [
            'must' => [
              ['term' => ['my_field' => 'abc']],
              ['range' => ['my_field' => ['gte' => 5, 'lt' => 10]]]
            ]
          ]
        ]
      ]
    ]
  ]
];

$results = $client - > search($params);
```

The docs are a bit sparse (details about [bool query](http://www.elasticsearch.org/guide/en/elasticsearch/client/php-api/current/_search_operations.html#_bool_queries) and [filtered query](http://www.elasticsearch.org/guide/en/elasticsearch/client/php-api/current/_search_operations.html#_a_more_complicated_example)) on building queries, but that's just because it follows the ES JSON api 1:1.  If you construct a JSON query, you can translate it directly into a PHP array with the same representation.  You can even `json_encode()` it :)
