### ISSUE TITLE
Taking Top Documents based on Score

### ISSUE THREAD

**Issue by JugalSA** [elastic/elasticsearch-php#199]
I want to know that if i have 100 results for a particular search with their individual elasticsearch score.
And i want to take only 60% of the highest score document for every search. How to do that in ES.
"Size" parameter wont work in my case because search is dynamic.
So lets say i have a document with highest score 2.1480842 then i want documents which has score greater than 1.28885052...

**Comment by polyfractal** [comment]
Oops, responded in the other thread.  Here it is again :)

I want to know that if i have 100 results for a particular search with their individual elasticsearch score.
I'm not sure I understand this question? The search hits always come back with the score for that document.

And i want to take only 60% of the highest score document for every search. How to do that in ES.
I'm afraid there is no real way to do this server-side. Scores are always calculated in the context of the search results. Meaning it is basically impossible to compare the scores between two queries, because the factors that affect the score change for each query (term and document frequencies, etc).

In terms of technical aspect, there is no way to ask ES to provide 60%, because it only maintains priority queues which are sized to fit the size + from parameter. To calculate 60%, Elasticsearch would have to keep all doc scores resident in memory to know where the 60% spot lands. Which would be very expensive.

Theoretically, the only way to do this is to request all search hits by setting an enormous side, then pruning the results client-side. But that's equally expensive for ES, and forces your app to handle potentially very large responses.

Basically, it's not really possible, nor is it a good idea :)

**Comment by polyfractal** [comment]
Closing...but feel free to reopen if you have further questions!
