### ISSUE TITLE
About search queries

### ISSUE THREAD

**Issue by marciomansur** [elastic/elasticsearch-php#200]
Hello,

I'm new on elasticsearch, so, I don't know much about this search engine. So, I'm having some trouble in the search.

My query returns aways just 10 records, and I'm following the documentation. How can I receive all data in a "type" (collection) ?

**Comment by polyfractal** [comment]
To paginate, you can use the `from` and `size` parameters:

```php
$query = [
    'index' => 'my_index',
    'type' => 'my_type',
    'from' => 0,    // Start at the first document
    'size' => 100,  // Show 100 documents
    'body' => [
        'query' => [
            'match' => [
                'category' => 'pie'
            ]
        ]
    ]
];

$results = $client->search($query);
```

However, it's not a good idea to return *all* results.  Search results rank (sort) documents based on their relevance to the query.  Since there is a complete ordering of results, documents cannot be streamed out of the datastore...they need to be loaded and sorted into memory in order.  This means that requesting *all* documents is much more expensive in a search engine than from a database, which just uses a cursor to iterate over matching (but essentially random) documents.

You can read more details here:  http://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html

**Comment by polyfractal** [comment]
Closing...but feel free to reopen if you have further questions!
