### ISSUE TITLE
Many to Many relations

### ISSUE THREAD

**Issue by marciomansur** [elastic/elasticsearch-php#212]
Hello,

I have two tables (these tables will be indexed): groups and pages. Groups can have many pages, otherwise pages can be inside many groups. Something like this:

pages:
id
url
name

groups:
id
description

pages_groups_pivot:
id
page_id
group_id

Index independent pages and groups is easy, but, how can I handle Many to Many relations? 
What is the best way to do that?

**Comment by polyfractal** [comment]
Truthfully, there isn't a good way to handle many-to-many relations in Elasticsearch.  Search engines are not relational databases, and so the relational support is minimal.  This is doubly true because Elasticsearch only supports features which scale horizontally, and distributed joins are *very* expensive.

Elasticsearch supports one-to-many relations with parent/child and nested features.  For the many-to-many use-case, you'll likely have to start denormalizing data and dealing with the logistical complexity yourself (e.g. updating fields when a parent changes, etc).

This chapter in the Definitive Guide might help with some more background: http://www.elastic.co/guide/en/elasticsearch/guide/master/relations.html

**Comment by polyfractal** [comment]
Closing, feel free to reopen if you have more questions.

**Comment by akkivaghasiya5** [comment]
Hello polyfractal,

I have similar confusion like this. I have two tables in MySql. i.e, users and projects. users is parent and projects are child (One-Many). But I don't know that how should I index these data in Elasticsearch? Should I use nested feature (as you told [here](https://github.com/elastic/elasticsearch-php/issues/212#issuecomment-90074218)) or should I create two types in index. i.e, users type and projects type? Please consider that I have to do all these stuffs (insert, update, delete, search like MySql JOIN) related to MySql. I think query string like MySql JOIN may not possible in elasticsearch. If I'm right, can you please help me by providing demo for this query. i.e, find all the users with projects whose name is like %olyfract%.
