### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by charuag** [elastic/elasticsearch-php#215]
Does ES provide this functionality to return autocomplete suggestions with the filter name. For eg, In my document

```
"_index":1,
"_type":"xyz",
"_source":{
    "author":"John Doe",   
}
```
Now if I search for "John" in the autocomplete it should return "author:John Doe".

**Comment by polyfractal** [comment]
There are a couple ways you can do it.

- Simply search against a field, and if it matches, return the value as a suggestion.  This works well for exact matches against individual tokens
- Use something like [match_phrase_prefix](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#_match_phrase_prefix) to match fragments of what the user is typing, such as "Joh" matching "John Doe".  Basically "as you type" suggestions
- Use the [Term](http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-suggesters-term.html) or [Phrase Suggester](http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-suggesters-phrase.html) to introspect your data and provide automatic suggestions.  Term suggester is essentially typo correction ("Did you mean XYZ" that google displays), while Phrase is more like ("Also try these search phrases" that google provides at the bottom of results).
- [Completion suggester](http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-suggesters-completion.html) for fully manual suggesting "as you type", but also very fast.  On the order of 1-2ms for each suggestion, basically limited by network speed at that point.

The simplest approach is to execute a search on specific "suggestion" fields (such as `author`) and providing the source to the user if there is a match.  This requires a full search and network transfer, so it can be a bit too slow sometimes.  That's why the Term, Phrase and Completion suggester were added for various purposes.

**Comment by charuag** [comment]
Thanks for your answer! However, in my use case I don't know the field on which I want to autocomplete. As, user types "John" ES should return autocomplete suggestions as say "name: John K", "author: John Doe", "title: John is a writer".

```
"_index":1,
"_type":"xyz",
"_source":{
    "author":"John Doe",
},
"_index":1,
"_type":"xyz",
"_source":{
    "name":"John K",
    "title":" John is a writer",
}
```

Please suggest if this can be done in ES.

**Comment by polyfractal** [comment]
Sure it can :)

It's the same list as before, you just need to expand it to work with multiple fields.  E.g. run a `multi_match` on all your fields, then return them any highlighted fragments that matched.  Or dump all your "suggestion text" into a single `suggest` field (using something like `copy_to`, or just have your app do it) then use any of the single-field suggesters (Term, Phrase, Completion, match_phrase_prefix) run off that single combined field.

It's the same idea, just a little more complicated because you either need to deal with multiple fields, or combine multiple fields into one field.

**Comment by charuag** [comment]
Thanks! I think this would solve it! I was checking this [multi_match](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html) query samples. Couldn't find any example like to multi_match on all dynamic fields "*".

```
{
  "multi_match" : {
    "query":    "this is a test", 
    "fields": [ "*" ] 
  }
}
```

**Comment by polyfractal** [comment]
Yep, you can use a star in `multi_match`. Only thing to watch out for is that the star will also match "internal meta" fields, like `_id`, `_timestamp`, `_ttl`, etc.

**Comment by charuag** [comment]
Can you give any example on multi_match on "*" and then copy_to on highlighted fields.
