### ISSUE TITLE
Extending the Client class

### ISSUE THREAD

**Issue by cviebrock** [elastic/elasticsearch-php#239]
Here's my scenario: I'm hoping to be able to use a custom Client class that auto-prefixes the `index` parameter for every request.  In our case, it's to be able to store both "beta" and "live" data for the same application on one ES instance.

I'm using the official 2.0 client, and am running into problems no matter how I try and go about doing this.

I figure the easiest way would be to someone overload the `extractArgument()` method and do something like:

``` php
<?php namespace Cviebrock\LaravelElasticsearch;

use Elasticsearch\Client as BaseClient;

class Client extends BaseClient {

    public $prefix = 'foo';

    public function extractArgument(&$params, $arg) {

        $value = parent::extractArgument($params, $arg);

        if ($arg == 'index') {
            $value = $this->prefix . '_' . $value;
        }

        return $value;
    }
}
```

In this case, I need the official ClientBuilder class to return my class from its `build()` method instead of the official client.  To do this, I'd need to extend the ClientBuilder class as well, and do something like:

``` php
<?php namespace Cviebrock\LaravelElasticsearch;

use Elasticsearch\ClientBuilder as BaseClientBuilder;


class ClientBuilder extends BaseClientBuilder {

    public function build() {

        // make the parent class do all the building
        parent::build();

        // but return our own client class, where we can modify some behaviours
        return new Client($this->transport, $this->endpoint);
    }
}
```

The problem here is that `$this->transport` and `$this->endpoint` are private properties, so my extended class doesn't have access to them.  Nor are there getters I could use.

So ... I guess my request would be to either make those properties protected instead of private, or define some configurable way to determine what class the builder actually builds (maybe enforce it via an ClientInterface).

Unless there is another solution that I'm not thinking of?

Thanks!

**Comment by polyfractal** [comment]
On the run, so haven't looked at the code too closely yet.

Is the prefix supposed to apply to *every* request, including requests like Node Stats?  If so, the easiest way is to just pass it in as a URL path while constructing the hosts:

```php
$hosts = [ 'localhost:9200/beta_' ];
$client = ClientBuilder::create()->setHosts($hosts)->build(); 
```

When the connection URI [is parsed](https://github.com/elastic/elasticsearch-php/blob/2.0/src/Elasticsearch/ClientBuilder.php#L498), all components (including the path) are passed down to the Connections.  The default Connection will [automatically prepend the path](https://github.com/elastic/elasticsearch-php/blob/2.0/src/Elasticsearch/Connections/Connection.php#L109-L111) (e.g. `/beta_`) to all outgoing requests.  However, it also means that non-index based requests are prepended too.  E.g. `GET /_nodes/stats` becomes `GET /beta_/_nodes/stats`.

If you want/need to override the `extractArguments` method, due to a design quirk you'll also have to override the same method in the `AbstractNamespace` class too.

Potentially less invasive, you could use a Decorator approach and just "wrap" the client.  Since you are basically only modifying the URL, you don't really need to extend/override anything to do that.  Instead:

```php
class MyClient {
    
    private $client;
    private $prefix;

    public function __construct(Elasticsearch\Client $client, $prefix)
    {
        $this->client = $client;
        $this->prefix = $prefix;
    }

    // Decorate all methods with our custom prefix
    public function __call($name, $arguments)
    {
        if (isset($arguments['index']) === true) {
            $arguments['index'] = $this->prefix . '_' . $arguments['index'];
        }
        
        return $this->client->$name($arguments);
    }
}
```

It works well if you only want to change certain endpoints too:

```php
class MyClient {
    private $client;
    private $prefix;

    public function __construct(Client $client, $prefix)
    {
        $this->client = $client;
        $this->prefix = $prefix;
    }

    // The method we want to decorate with our custom URL
    public function index($params)
    {
        $params['index'] = $this->prefix . '_' . $params['index'];
        return $this->client->index($params);
    }

    // Everything else we don't care about
    public function __call($name, $arguments)
    {
        return $this->client->$name($arguments);
    }
}
```

Note:  both of these only decorate the "main" namespace, you'd have to do similar for other namespaces, or extend / inject those namespaces.

With all that said, I like being able to inject the Client class itself.  Hadn't thought of it before, but it fits naturally with the 2.0 design.  And marking transport / endpoint as protected is probably ok...would need to look at it closer to make sure, but I don't see the harm.

Finally, you could override and inject your own Connection to add the prefix, but at that point the connection path method at the top is easier for the same effect.
