### ISSUE TITLE
Delete document type from index

### ISSUE THREAD

**Issue by henninghorn** [elastic/elasticsearch-php#256]
Is there any way to delete certain document types from an index?
If a have a "site" index, containing the types "articles", "comments", "users" etc.

I know this is the command for it, but I can't find the equivalent of that in this package
````
curl -XDELETE 'http://localhost:9200/twitter/tweet
````

Have is missed something?

**Comment by polyfractal** [comment]
Yeah, the functionality is just [poorly named](https://github.com/elastic/elasticsearch-php/issues/101#issuecomment-50033138) I'm afraid.  It's a naming issue with Elasticsearch, since we follow the same naming convention to keep things as similar as possible.

You need to use the Delete Mappings API:

```php
$params = [
  'index' => 'my_index',
  'type' => 'my_type'
];

$client->indices()->deleteMapping($params)
```

**Comment by henninghorn** [comment]
Ah, I see. Thanks!
