### ISSUE TITLE
How to configure curl connect timeout?

### ISSUE THREAD

**Issue by TheHett** [elastic/elasticsearch-php#259]
Hi,
I do not understand, how to pass "timeout" param to transport connection? Its possible?
Using param "timeout" in method "search" no give effect.

**Comment by polyfractal** [comment]
Yeah, the search `timeout` param is the Elasticsearch timeout.  E.g. how long a node should wait for a shard response before returning.

If you want a curl connection timeout, you can do it two ways (assuming you are using the default Guzzle connection):

```php
$params['guzzleOptions']['command.request_options'] = [
    'connect_timeout' => 2.0,
    'timeout' => 2.0
];
$client = new Elasticsearch\Client($params);
```

Or raw curl options:

```php
$params['guzzleOptions'] = [
    'curl.options'=> [
        CURLOPT_CONNECTTIMEOUT => 2.0
    ]
];
$client = new Elasticsearch\Client($params);
```

Unfortunately, these can only be set when the connection is instantiated at the moment.  No technical reason, other than it hasn't been fixed to be per-request yet.  ES-PHP 2.0 allows per-request options (or at least it should...been a while since I've looked at it)

**Comment by TheHett** [comment]
:+1: thank you very much

**Comment by TheHett** [comment]
@polyfractal 
Hi, you are sure that here
https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Common/DICBuilder.php#L291
need use array_merge? I suspect it need array_merge_recursive

**Comment by harpreetsb** [comment]
how to do this in ES2 syntax?

**Comment by polyfractal** [comment]
@harpreetsb In ES-PHP 2.x the timeout is now specified per-request.  See the documentation here:  https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_per_request_configuration.html#_curl_timeouts

```php
$client = ClientBuilder::create()->build();

$params = [
    'index' => 'test',
    'type' => 'test',
    'id' => 1,
    'client' => [
        'timeout' => 10,        // ten second timeout
        'connect_timeout' => 10
    ]
];
$response = $client->get($params);
```

**Comment by TheHett** [comment]
@polyfractal thx!
