### ISSUE TITLE
Inefficiency in SniffConnectionPool 

### ISSUE THREAD

**Issue by DhavalKapil** [elastic/elasticsearch-php#261]
In SniffConnectionPool:
```
if ($connection->isAlive() === true || $connection->ping() === true) {
    return $connection;
}
```
Shouldn't the client first see if all connections are alive and ping them only if none is alive? Suppose the first 4 connections selected by the selector are dead then time wasted = `$pingTimeout * 4` which would be 4 seconds.

**Comment by polyfractal** [comment]
This basically boils down to a a general-case vs worst-case debate.

In the general case, the vast majority of your nodes will be online and responsive.  With the current setup, we keep network chatter to a minimum because it uses the first node it finds.  This does become slower in the worst-case, where many nodes are missing and it has to repeatedly ping multiple machines.  But since that should be a relatively rare event, it shouldn't really be optimized for.

Also note that if you have 150 nodes, you would have to ping 150 nodes as soon as the client initializes.  This is especially problematic because PHP cannot share connections between scripts (PHP is inherently shared-nothing architecture), and many PHP scripts are very short lived, such as loading a page and then exiting.  The latency would be intolerable if each page load had to first ping 150 nodes.

Of course, this is just the default, and it is pluggable  --  so feel free to write your own connection pool for your own scenario.  That's exactly why all the clients are pluggable, because we can't anticipate or optimize for all use-cases :)

**Comment by DhavalKapil** [comment]
I get your point :+1:
