### ISSUE TITLE
CurlMultiConnection doesn't filter credentials from log

### ISSUE THREAD

**Issue by jrbasso** [elastic/elasticsearch-php#277]
On the [CurlMultiConnection](https://github.com/elastic/elasticsearch-php/blob/v1.3.4/src/Elasticsearch/Connections/CurlMultiConnection.php#L156) the log send all the parameters, which includes the auth credentials. 

This logs as debug, but allow the logger to extract and expose it improperly. Probably having just the username on the log would be fine.

**Comment by polyfractal** [comment]
Chatted with some of the other client devs and agreed this is a problem.  Will get this fixed shortly

**Comment by polyfractal** [comment]
Fixed in 56b4a3a and tagged in v1.4.1.  

I opted to redact the entire auth string, since even the username leaking might considered a security issue for some.  Other clients remove the header completely, but I think it is useful to log that your client was at least *attempting* to use basic auth (even if you can't see the values), since that might be diagnostically useful.

It'll log "xxxx:xxxx" now.  Sorry for the delay!

**Comment by jrbasso** [comment]
Cool, thanks! :+1:
