### ISSUE TITLE
error_log flood if curl_multi_exec isn't allowed

### ISSUE THREAD

**Issue by jeabakker** [elastic/elasticsearch-php#280]
Using the 1.x branch

We encountered a situation where curl_multi_exec was disabled in php.ini. When trying to connect to a host even the $client->ping() caused +/- 150mb of errors in the error_log before the script was timed out.

I know you can't check for the availability of every function that is used, but flooding an error log could maybe be prevented? (I hope)

**Comment by polyfractal** [comment]
Hm, I'm not sure if there is anything we can do about the log itself.  But we could add a check upfront to client initialization for the key functions needed (e.g. if curl is installed but `curl_multi_exec` isn't enabled, the client is inoperable anyway).  The 2.0 branch has a similar check on instantiation.

So instead of a 150mb logs, you'd just get one fatal exception up front.  I think that sounds more reasonable?

It won't protect against other exceptions that spam the log (like an inaccessible cluster), but I don't think there is anything to be done about that short of writing a custom `ThrottlingHandler` which throttles repeated logging.

**Comment by jeabakker** [comment]
> So instead of a 150mb logs, you'd just get one fatal exception up front. I think that sounds more reasonable?

+1

**Comment by polyfractal** [comment]
Fixed in a12839c and tagged in v1.4.1.

Sorry for the delay!
