### ISSUE TITLE
Update Guzzle

### ISSUE THREAD

**Issue by electrickite** [elastic/elasticsearch-php#288]
Guzzle version 3 is specified in composer.json. Guzzle has since moved on to version 6 and implemented PSR-7. This makes it difficult to use an up-to-date Guzzle client in other areas of a project while using elasticsearch-php.

**Comment by reafle** [comment]
+1, could not simply `composer require elasticsearch/elasticsearch ~2.0@beta` without getting into guzzle dependency hell

**Comment by polyfractal** [comment]
Have you tried the 2.0 beta branch?  It is based on Guzzle 5 (more specifically, it uses Guzzlehttp/RingPHP).  It doesn't implement PSR-7 because the branch was started before PSR-7 was a thing, but since the dependency is just for RingPHP I think it should play nicer?  Especially since Guzzle6 has abandoned RingPHP entirely...

My goal is to un-beta 2.0 this week and make it a legit release.  Been stuck in beta too long, which is my fault :(

Or are your problems stemming from interfacing PSR-7 code with non-PSR-7 code?

**Comment by electrickite** [comment]
@polyfractal I have not tried the 2.0 branch, but glad to hear it's moving along!

There are really two problems here. One is more of a feature request: it would be nice to be able to use this library interchangeably with PSR-7 compliant code. Not a huge deal, though, since we could always use a wrapper around elasticsearch responses.

The bigger issue is that using ES-php prevents using another version of guzzle via composer. Since Guzzle is such a popular library, this can be a headache. Moving to v5 is progress, though!

**Comment by polyfractal** [comment]
Ok, cool.  Definitely hear you about the Guzzle3 headache, moving off it has been stalled for too long!  I'll give you a poke when ES 2.0 is officially tagged and released.  It should fix the dependency hell problem, since it doesn't depend on any actual Guzzle client components, just the internal RingPHP guts.

I've only skimmed the PSR-7 spec, but I think we could probably make the responses PSR-7 compliant without too much trouble.  Which would at least help if/until Guzzle6 is integrated.

**Comment by polyfractal** [comment]
@electrickite Just merged 2.0 into master and tagged `v2.0.0`.  The only guzzle-related dependency is now `"guzzlehttp/ringphp" : "~1.0"`, which shouldn't affect Guzzle6 (I don't think).

Let me know if that helps with your dependency problems!

**Comment by polyfractal** [comment]
Closing, lemme know if you have any problems/questions :)
