### ISSUE TITLE
Complicated Configuration v2.0

### ISSUE THREAD

**Issue by designermonkey** [elastic/elasticsearch-php#294]
Why on earth has the configuration been made so complicated?

I have just come to a new project requiring ES, and after being able to provide an array of configuration options (so simple) I now have to break my config array apart, check for certain properties and then call static methods on a client builder.

Really? Can this not be simple please?

**Comment by designermonkey** [comment]
This from the docs for v1.0 is perfect and all that is needed.

```php
$params = array();
$params['hosts'] = array (
    '192.168.1.1:9200',                 // IP + Port
    '192.168.1.2',                      // Just IP
    'mydomain.server.com:9201',         // Domain + Port
    'mydomain2.server.com',             // Just Domain
    'https://localhost',                // SSL to localhost
    'https://192.168.1.3:9200',         // SSL to IP + Port
    'http://user:pass@localhost:9200',  // HTTP Basic Auth
    'https://user:pass@localhost:9200',  // SSL + HTTP Basic Auth
);

$client = new Elasticsearch\Client($params);
```

Anything more complicated than this will just make people rethink ES in PHP.

**Comment by polyfractal** [comment]
Hm, I see your point from an automation point of view.  The builder allowed me to externalize all the dependency management and wire the client up-front, which allowed me to ditch Pimple.  It also simplified how modules are injected into the client.

The fact that it's chained is just a side effect from the builder pattern and me writing stuff by hand (instead of inside an application)

How about a method on the builder that accepts an array of values and constructs from that?  E.g. something like this:

```php
// Static variety
$client = ClientBuilder::fromConfig($my_array);

// Or perhaps a method in case you also want to chain/override some things
$client = ClientBuilder::create()->setConfig($my_array)->build();
```

> This from the docs for v1.0 is perfect and all that is needed.

As an aside, if you only need to set hosts, it isn't that bad currently:

```php
$client = ClientBuilder::create()->setHosts($hosts)->build();

// Static is just sugar to simplify builder creation:
$client = (new \Elasticsearch\ClientBuilder())->setHosts($hosts)->build();
```

**Comment by designermonkey** [comment]
> How about a method on the builder that accepts an array of values and constructs from that?

That would be great. Thanks @polyfractal

**Comment by polyfractal** [comment]
Awesome.  This is on my shortlist to get fixed this week, as well as a few other fixes (the open security issue, and the spammy log issue).  I'll ping this thread once it get's tagged!

**Comment by polyfractal** [comment]
Took a bit longer to get to this than I hoped, sorry.  Let me know how this works for you, I tagged it as a patch version (`v2.0.1`) since it doesn't really break anything (although not strictly a bug fix but whatever, semver only half works)

Array keys correspond to their method name, e.g. `retries` corresponds to `setRetries()`:

```php
$params = [
    'hosts' => [
        'localhost:9200'
    ],
    'retries' => 2,
    'handler' => ClientBuilder::singleHandler()
];
$client = ClientBuilder::fromConfig($params);
```

If you have extra, unknown params in the array (e.g. you are using it for something else in addition to setting up the client), you can set $quiet = true to silence exceptions.

```
```php
$params = [
    'hosts' => [
        'localhost:9200'
    ],
    'retries' => 2,
    'imNotReal' => 5
];
$client = ClientBuilder::fromConfig($params, true);
```
`
