### ISSUE TITLE
Update vs Create/Index

### ISSUE THREAD

**Issue by designermonkey** [elastic/elasticsearch-php#298]
How come update requires the body to have a `doc`, while the other crud methods don't?

Any room for consistency here?

**Comment by polyfractal** [comment]
Yeah, it's a quirk in the ES api itself.  It's because you can include "metadata" about the update, such as scripts or upserts, e.g.

```
# plain doc update
POST /test/type1/1/_update
{
    "doc" : {
        "name" : "new_name"
    }
}

# With detect_noop
POST /test/type1/1/_update
{
    "doc" : {
        "name" : "new_name"
    },
    "detect_noop": true
}

# With  doc_as_upsert
POST /test/type1/1/_update
{
    "doc" : {
        "name" : "new_name"
    },
    "doc_as_upsert": true
}


# With  script / params / upsert
POST /test/type1/1/_update
{
    "script" : "ctx._source.counter += count",
    "params" : {
        "count" : 4
    },
    "upsert" : {
        "counter" : 1
    }
}
```

etc etc.   Basically, because the ES API mixes partial-doc updates with scripts and optional params, it needs to stick the document in a special namespace.  Otherwise it's unclear what is a JSON document vs scripts vs a JSON document that has fields called `"script"`, etc.

The other CRUD operations don't have this problem because they either don't have options (DELETE) or they have simple options that are expressed through the URI (e.g. index vs create).

**Comment by designermonkey** [comment]
I see, no problem then, thanks for the answer.

**Comment by polyfractal** [comment]
Np.  I agree it is less than ideal :(
