### ISSUE TITLE
@throws in docs

### ISSUE THREAD

**Issue by designermonkey** [elastic/elasticsearch-php#299]
Is there any scope to add `@throws` statements into the php doc comments?

I'm trying to get a handle on what I should be catching, and first port of call was the Client class, but now I have to dig deeper.

**Comment by polyfractal** [comment]
Hm, yeah, the docblocks should probably annotate this better.  The "problem" is that most endpoints can throw most exceptions, so the docblocks would essentially list 90% of the exceptions.  E.g. any particular endpoint could throw (just randomly picking some):

- NoNodesAvailableException -- any request when you run out of live nodes
- NoShardAvailableException -- any request that hits a red shard
- MaxRetriesException -- any request that runs out of retries
- BadRequest400Exception -- any request with an invalid request body
- All the curl exceptions (CouldNotConnectToHost, CouldNotResolveHost, OperationTimeoutException)

And some that are semi-specialized ones that cover many but not all endpoints:

- 404MissingException any indexing command that requires a specific ID, or any request against a missing index, or against missing templates, scripts, percolators, etc.  
- ScriptLangNotSupportedException -- Any search or update that uses a script not configured

What could be improved is the exception hierarchy.  The hierarchy is *supposed* to look like this:

- ElasticsearchException
 - TransportException
   - ServerErrorResponseException: All 500-level server exceptions (e.g. tried to access a red shard)
   
    - ClientErrorResponseException: All 400-level errors (e.g. caused by bad request bodies)
 - InvalidArgumentException, RuntimeException, etc.  Exceptions caused by the client, not ES

But right now the inheritance tree is all over the place.  I just had a look and it's really sloppy and inconsistent (some extend their parent, some extend Exceptions directly, some extend random middle-tier exceptions).

I'm open to suggestions, I'm really not sure how best to annotate everything.  Thoughts?

**Comment by designermonkey** [comment]
Hmm, ok then, I would have an endpoint method in a higher level class define that it throws an instance of the lowest common exception as something like:

```
@throws TransportException  when one of many exceptions occur
@see      Classname::method
```

That way the reader can be directed to the classname that this method is a proxy for. There is always `@uses` to do a similar thing, so all the methods in use can be referenced.

I guess the key is the Exception hierarchy being correct to make that work, so at least people can catch the highest level in code, and read more into the docs for specific cases.

**Comment by ezimuel** [comment]
@designermonkey I think the best approach is still to use a hierarchy of Exception model. I've refactored the code a little bit in 7.0 and I've plan to rewrite it using a new Exception model for 8.0. Let me know if you have still feedback on this issue, thanks!
