### ISSUE TITLE
Unexpected 503 status on count request.

### ISSUE THREAD

**Issue by fvovan** [elastic/elasticsearch-php#303]
I found very weird behavior during execution of ```count``` method.
The sequence is following
1. I create index.
2. I try to call ```count``` on it (for all types) directly after creation (also tried to do ```refresh``` but no effect).
3. Get ```\Elasticsearch\Common\Exceptions\ServerErrorResponseException``` with 503 status code but in fact response returns correct data ```{"count":0,"_shards":{"total":5,"successful":0,"failed":0}}```

If I add at least I document to index, count request is performed right.

Using the same sequence in plain curl interface to elasticsearch gives expected results (e.g. the same response but 200 status)

PHP 5.4.36
ElasticSearch 1.3.1
elasticsearch-php 2.0.2

**Comment by polyfractal** [comment]
Heya @fvovan, sorry for the delay, was on holiday.

Are these commands being executed quickly in an automated fashion (e.g. setup code, integration test, etc)?  I suspect you are seeing the 503 because one or more shards have not finished initializing when the `count` command is being executed.  

The create index API is asynchronous...it will return before all shards have been created around the cluster.  It's not uncommon for integration tests to fail due to this slight delay.  You can simulate it like this:

```shell
# Disable allocation to artificially prevent the cluster from allocating shards
➜ curl -XPUT 'http://localhost:9200/_cluster/settings' -d '{
    "transient" : {
        "cluster.routing.allocation.enable" : "none"           
    }
}'
{"acknowledged":true,"persistent":{},"transient":{"cluster":{"routing":{"allocation":{"enable":"none"}}}}}

# Create the index
➜  curl -XPUT localhost:9200/test
{"acknowledged":true}

# Check the health to confirm red (no shards allocated)
➜  curl -XGET localhost:9200/_cluster/health  
{"cluster_name":"elasticsearch","status":"red","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":10}

# Execute the count API and see a 503
➜  curl -i -XGET localhost:9200/test/_count
HTTP/1.1 503 Service Unavailable
Content-Type: application/json; charset=UTF-8
Content-Length: 59

{"count":0,"_shards":{"total":5,"successful":0,"failed":0}}
```

You can safeguard against this by using the `wait_for_status` flag on the cluster health API, which will block until the status is satisfied:

```shell
curl -XGET localhost:9200/_cluster/health?wait_for_status=yellow
```

And in PHP:

```php
$client->cluster()->health([
  'wait_for_status' => 'yellow'
]);
```

**Comment by fvovan** [comment]
thanks a lot!

**Comment by polyfractal** [comment]
Closing, lemme know if you have any more questions/problems! :)
