### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by bLACKLOTUS90** [elastic/elasticsearch-php#307]
Hi.

So I'm having this error:

Catchable fatal error: Argument 1 passed to Elasticsearch\Client::__construct() must be an instance of Elasticsearch\Transport, none given, called in C:\wamp\www\dafuk\index.php on line 4 and defined in C:\wamp\www\dafuk\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Client.php on line 68

I read and read again the installation and configuration, but I just can't move on. It always says none given, array give, string given, etc... 

Can someone explains me how to make this work?

**Comment by ruflin** [comment]
@bLACKLOTUS90 Can you post the code you are using in index.php?

**Comment by bLACKLOTUS90** [comment]
Hello. So my index.php has this: 

require 'vendor/autoload.php';
$client = new Elasticsearch\Client();

**Comment by polyfractal** [comment]
Hey there @bLACKLOTUS90, sorry for the delay...I was on holiday.

It looks like you've installed the 2.0 branch of the client, but are using the instantiation method for 1.0.  Instead, try this:

```php
require 'vendor/autoload.php';
$client = ClientBuilder::create()->build();
```

**Comment by bLACKLOTUS90** [comment]
Fatal error: Class 'ClientBuilder' not found in C:\wamp\www\dafuk\index.php on line 3 

Now I get this :(

And even when I install 1.0, I got same Transport error.

**Comment by polyfractal** [comment]
Sorry, you'll need to import the classes too.  My IDE does it for me, so I totally forgot.  I'll update the docs too, since that should be listed explicitly.  Try this, on the 2.0 branch:

```php
require 'vendor/autoload.php';

use Elasticsearch;
use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()->build();
```


If that doesn't work, could you share your `composer.lock` file?  I suspect something is going wrong with your composer installation (unrelated to the client creation problem).  For example, if you installed the 1.0 branch, it is impossible to get the same Transport error (the 1.0 branch creates its own Transport object, so that error is literally impossible to receive).  This suggests to me that you still have the 2.0 branch installed, and may be doing something wrong with Composer.

**Comment by sancoLgates** [comment]
thanks, it works :+1:

**Comment by krtrth** [comment]
tried it still not working 
error:

FatalThrowableError in Utility.php line 385:
Class 'Elasticsearch\ClientBuilder' not found

**Comment by polyfractal** [comment]
@krtrth Did you include the composer autoloader?

```php
require 'vendor/autoload.php';
```
