### ISSUE TITLE
Client::SetParams() -> broken dic

### ISSUE THREAD

**Issue by dev-head** [elastic/elasticsearch-php#311]
Hi,

There is an undocumented configuration option for using our own dic with this client. This is great, being able to use my own dic instead of yours makes me very happy. Not that your dic is bad, I don't mean that at all. I have quite enjoyed going over it and using it for a while now, I just need more out of it is all. 

So here I am, my dic all ready to go; when I try to pass it in, it broke. Looks like we just need to allow for a new dic. 

branch: 1.0
file: src/Elasticsearch/Client.php
method: setParams();

### Current implementation 
```
        if (isset($params['dic']) !== true) {
            $dicBuilder =  new DICBuilder($hosts, $params);
        } else {
            $dicBuilder = $params['dic']($hosts, $params);
            unset($params['dic']);
        }
```

#### Suggested implementation 
```
        if (isset($params['dic']) !== true) {
            $dicBuilder =  new DICBuilder($hosts, $params);
        } else {
            $dicBuilder = new $params['dic']($hosts, $params);
            unset($params['dic']);
        }
```

**Comment by polyfractal** [comment]
Yep, custom dependency injection was added so that I could [mock certain things](https://github.com/elastic/elasticsearch-php/blob/1.0/tests/Elasticsearch/Tests/ClientTest.php#L130-L143), but never officially documented because it's clumsy and not a great injectable system (as compared to the system in 2.0 for example).

The way it work is to provide set `$params['dic']` to a closure that returns a new DI container based on host/params.

So instead of providing a new object, you can do something like this:

```php
$params = array(
    'dic' => function ($hosts, $params) use ($other) {
        return new MyDIContainer($host, $params, $other);
    }
);
$client = new Elasticsearch\Client($params);
```

Does this work for you?  I'd prefer not making a change to this if possible because it would break bwc, even though it was undocumented, other people may be relying on it.

**Comment by polyfractal** [comment]
Closing for now, since there is a workaround and it doesn't break backwards compatibility.  Please feel free to reopen if this doesn't work for some reason :)
