### ISSUE TITLE
inconsistent num of document between _cat/indices and <index>/_search 

### ISSUE THREAD

**Issue by veeruborra** [elastic/elasticsearch-php#365]
i inserted one document in elasticsearch.
when i search in indices it showing

http://localhost:9200/_cat/indices?v
health status index pri rep docs.count docs.deleted store.size pri.store.size 
green open mylogs 5 1 2 0 72.4kb 72.4kb

when searching in that index

http://localhost:9200/mylogs/_search

took: 1,
timed_out: false,
_shards: {
total: 5,
successful: 5,
failed: 0
},
hits: {
total: 1,
max_score: 1,
hits: [
{}]

**Comment by polyfractal** [comment]
Is this being run in an automated fashion?  E.g. a script which indexes a doc, then checks `_cat` then `_search` ?

Elasticsearch by default has a 1s refresh cycle.  Documents are available for real-time GET immediately (which is why `_cat` shows 1 document) but documents are not searchable until one second later.  See [Near Real Time Search section of the Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html) for more details.

If this is being run in an automated fashion, you can call a manual refresh after indexing the doc:

```php
$client->index([...]);
$client->indices()->refresh([...]);

$client->search([...]);
```

**Comment by veeruborra** [comment]
iam inserting single data in index.when checking in http://localhost:9200/_cat/indices?v   the count is twice.
but when searching in http://localhost:9200/mylogs/_search  the total is one.
whats the problem?

**Comment by polyfractal** [comment]
Are you using nested documents?  That will show extra documents, as each "nested" object counts as a single document internally.  E.g.:

```js
PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "user": {
          "type": "nested" 
        }
      }
    }
  }
}

PUT my_index/my_type/1
{
  "group" : "fans",
  "user" : [
    {
      "first" : "John",
      "last" :  "Smith"
    }
  ]
}

GET _cat/indices?v
```
```
health status index     pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   my_index    5   1          2            0      3.9kb          3.9kb 
```

Otherwise, you'll have to provide more information.  The details you are providing are just not descriptive enough for me to help you.  Please include a step-by-step recreation so that I can help you debug the problem.

**Comment by veeruborra** [comment]
yes.i got it.
In my mappings
PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "user": {
          "type": "nested" ,
 "properties": {

}
        }
      }
    }
  }
}
