### ISSUE TITLE
Problem with _bulk indexing

### ISSUE THREAD

**Issue by danielpoe** [elastic/elasticsearch-php#385]
We are using the default bulk feature

Something like this is used in the code:

`
$this->client = ClientBuilder::fromConfig($this->settings['client']);

....

// foreach documents loop: 
$bulkCommands[] = [
	'index' => [
		'_index' => $indexDocument->getIndexName(),
		'_type' => $indexDocument->getTypeName(),
		'_id' => $indexDocument->getDocument()->getId()
	]
];
$bulkCommands[] = //some assoc array with the fields;
$res = $this->client->bulk(['body' => $bulkCommands]);

`

**Randomly we get an Exception:**

Exception: parse_exception: Failed to derive xcontent

**Trace:**
Elasticsearch\Connections\Connection->tryDeserializeError(Array, 'Elasticsearch\C...')

Elasticsearch/Connections/Connection.php(544): Elasticsearch\Connections\Connection->tryDeserialize400Error(Array)

Elasticsearch/Connections/Connection.php(257): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)

Composer/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)

Composer/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)

Composer/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)

Composer/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(278): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))

Composer/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(154): 
Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array, Object(Elasticsearch\Connections\Connection), Object(Elasticsearch\Transport), Array)

Composer/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest('POST', '/_all/_bulk', Array, '', Array, Object(Elasticsearch\Transport))

Composer/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(80): Elasticsearch\Transport->performRequest('POST', '/_all/_bulk', Array, '', Array)

Composer/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(744): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()

 Elasticsearch\Client->bulk(Array)

When we force the AbstractEndpoint->resultOrFuture implementation to use the async mode (and not to call recursive wait on FutureArrayInterface)  everything seems to work fine. Which may be a hint to a side effect..

Any ideas?

**Comment by polyfractal** [comment]
Hey there, sorry for the delay.  Been on the road for work over the last month.

My first thought is a bad bulk request in some capacity, since that's the exception that ES is returning (the parse_exception).  So either something supplied in the bulk request that is breaking things, or a bug in the client which is making it build bulks incorrectly.

Is this still occurring?  Would it be possible to get a `print_r` of `$bulkCommands` before it is sent to the server, so I can see if there is something amiss?

The second point about the `resultOrFuture` could very well be a bug, but I'm not sure how it relates.  It should (theoretically) resolve the future the same, and in either case the requests being executed against the server are identical...I'd expect to see some kind of client-side PHP error, not a parse_exception.

**Comment by polyfractal** [comment]
Closing due to staleness, please feel to reopen if oyu can provide some more info!
