### ISSUE TITLE
Unordered array save

### ISSUE THREAD

**Issue by vladan-me** [elastic/elasticsearch-php#397]
I believe this issue should be within elasticsearch-php because it's not really logical.
It seems like that order of an array is important when saving array within a document, imagine this situation:
```
$array_of_numbers = array(1,2);
// Which is the same as:
$array_of_numbers = array(0 => 1, 1 => 2);
// and:
$array_of_numbers_unordered = array(0 => 1, 2 => 2);

```
Saving the first one will work properly, the second one is giving mapping parser error:
"mapper_parsing_exception: failed to parse [field_name]"

I've tried to do array_unique() on values and suddenly lost order and was really confused why saving didn't work... I guess I need to reorder them manually, but probably it should be done on elasticsearch-php level.
Tested on elasticsearch 2.1.1 and 2.2.0

**Comment by polyfractal** [comment]
Key order is important due to how PHP's `json_encode()` treats associative arrays.  If keys are omitted, or in-order and contiguous, the associative array is encoded to a JSON array via `json_encode()`.  If the keys are out-of-order or non-contiguous (gaps between keys), the array is encoded to a JSON object.  

This is because PHP doesn't really differentiate between dense arrays and hashmaps ... everything internally is a hashmap, and simply treated as an array if keys are in-order.

E.g.

Keys omitted
```php
$t = array('foo' => array(1,2));
echo json_encode($t);

{"foo":[1,2]}
```

With contiguous keys:
```php
$t = array('foo' => array(0 => 1, 1 => 2));
echo json_encode($t);

{"foo":[1,2]}
```

Keys non-contiguous
```php
$t = array('foo' => array(0 => 1, 2 => 2));
echo json_encode($t);

{"foo":{"0":1,"2":2}}
```

Contiguous but out-of-order
```php
$t = array('foo' => array(1 => 1, 0 => 2));
echo json_encode($t);

{"foo":{"1":1,"0":2}}
```


So you can see that depending on your input, PHP interprets them as different structures, which will affect Elasticsearch since the field is either mapped as a raw data type (string, integer, etc) or as a nested field.

I'm afraid there's not much we can do at the ES-PHP level though.  The client has to remain un-opinionated, and trying to infer which structure you meant (did you want an array?  A map?) would introduce a very large opinion.  And I don't think it could be done reliably anyway.

If you know everything should be dumped into a single array, and don't care about key order, you can use [`array_values`](http://php.net/array_values):

```php
$array_of_numbers = array_values($array_of_numbers);
```

Which will extract the values from the array and re-insert them with contiguous keys.

**Comment by vladan-me** [comment]
Hmm, ok, you are right, in this case array_values() is a way to go. Thanks for prompt response.

**Comment by polyfractal** [comment]
Np, happy to help!  I agree it is an unintuitive problem...I've run into the exact issue myself on several occasions :)
