### ISSUE TITLE
Delete all documents

### ISSUE THREAD

**Issue by MaurizioBrioschi** [elastic/elasticsearch-php#401]
### Summary of problem or feature request

Is impossible to delete all documents in a index

### System details

- Elasticsearch version 2.1 but i guess that that is a missing part/bug in the library

**Comment by polyfractal** [comment]
This is a limitation of Elasticsearch.  You can delete an entire index, or delete documents individually, but you cannot delete all the documents inside of an index (and keep the index).

This used to be possible with the Delete-by-Query functionality, but it was deprecated in 1.5: https://github.com/elastic/elasticsearch/pull/10859

There is now a Delete-by-Query plugin which you could try: https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/plugins-delete-by-query.html

**Comment by MaurizioBrioschi** [comment]
I think that it could be a very useful functionality because sometimes you need to preserve the index with the mappings and all the settings, but you need to remove all the documents and if you have a very big index it's crazy to remove documents one by one. 

It could be just a bulk operation or wrap the call inside **src/Elasticsearch/Endpoints/AbstractEndpoint.php**

**Comment by polyfractal** [comment]
Yep, it could be useful in certain situations, but it violates the core mandate of the low-level clients: represent the Elasticsearch API in an un-opinionated manner.  We don't have much leeway to introduce functionality like this, since it introduces a fairly strong opinion about how things should be done.

For example, what should the client do if other processes are writing to the index at the same time?  Should it only delete docs that were present at the start of the command?  Continue iteratively deleting all documents (and if yes, should it give up after a while if it never "catches up" to the new docs?)  Delete docs after a certain time period?  How should it handle failure?  Abort or continue trying to delete?  How does the client detect consistency issues when primaries/replicas are moved or promoted?

These are all open-ended questions and don't have a clear right or wrong answer, aka it's an opinion.  So in situations like this, we recommend people build the functionality on top of the low-level client.  These clients are meant to abstract away the basic, common functionality:  endpoint coverage, connection pooling and sniffing, etc.  Higher-order functionality (like "smart deletions") need to be handled upstream.

There is a Scan/scroll iterator helper (https://github.com/elastic/elasticsearch-php/tree/master/src/Elasticsearch/Helper/Iterators) which could help make this more ergonomic.  Pair the iterator up with bulk deletion and you're good to go. :)

As an aside, Delete-by-query was removed from ES core because it could introduce inconsistency.  The replacement plugin is now a scan/scroll + bulk deletes...basically identical to what a client would do anyway.

**Comment by MaurizioBrioschi** [comment]
I have got your point but i think that it's a responsibility of the developer to use a function like this carefully: it's like to say that in mysql i don't want to introduce *truncate* table command because it's dangerous...what happen if during a truncate table a client make an insert? We can solve this problem in many ways but the command truncate table is useful and must be present...

Of course, like you have already said... are just opinions

**Comment by polyfractal** [comment]
Closing, since this is outside the scope of the low-level clients.  Sorry!
