### ISSUE TITLE
Ingest Attachment Processor Plugin

### ISSUE THREAD

**Issue by SquareBeard** [elastic/elasticsearch-php#414]
Hello,

I'm trying to use the "[Ingest Attachment Processor Plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html)" to index content of files, but I can't figure out how to use it with elasticsearch-php.
Can someone points me in the right direction ?

Thank you

**Comment by polyfractal** [comment]
Sure.  The basic skeleton would look like this:

```php
$response = $client->ingest()->putPipeline([
    'id' => 'my_pipeline_id',
    'body' => [
        'description' => 'my attachment ingest processor',
        'processors' => [
            [
                'attachment' => [
                    'field' => 'my_field'
                ]
            ]
        ]
    ]
]);
```

E.g. use the `putPipeline()` method from the `ingest()` namespace.  Supply it with an ID, and in the body, a description and array of processors.  If you just want the one processor, there will be a single `attachment` object

**Comment by SquareBeard** [comment]
Thank you, that works !

As a side note, the documentation seems incorrect, the option `field` is now called `source_field`.

**Comment by SquareBeard** [comment]
Is there any other way to send the attachment to ES ?
I'm getting memory issues in the SmartSerializer when json encoding.

**Comment by polyfractal** [comment]
Not really.  You could use a different client (perl, python, .Net, etc), but fundamentally they are all doing the same thing: loading the document into memory, creating a JSON request and sending it over HTTP.

If your attachments are large, you'll likely need to increase PHP's memory limit.  In `php.ini` you can set the memory limit with: `memory_limit = 128M`.

Note: If you are using bulk requests, the entirety of the bulk sits in memory before it is sent to ES.  So if you are bulking large attachments at the same time, that could eat up a fair amount of memory.  You'll have to adjust your setting to suit.

**Comment by SquareBeard** [comment]
Ok, thank you.

**Comment by flip111** [comment]
@SquareBeard you could make a subclass of the `Connection class` and override [the part](https://github.com/elastic/elasticsearch-php/blob/fd3b0f16f7e09cb2096ef5f2d656c9fd8dd3d61d/src/Elasticsearch/Connections/Connection.php#L149-L151) which does the serializing (probably best to implement this as an alternative method, but that's up to you). You should then load your own Connection class before the default one, you [can do this with composer](http://stackoverflow.com/a/34600074). This has a few advantages:

1. less memory usage for json encoding. Because when your request looks like

```
PUT my_index/my_type/my_id?pipeline=attachment
{
  "data": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="
}
```
as described in [the docs](https://www.elastic.co/guide/en/elasticsearch/plugins/master/using-ingest-attachment.html). You can simple do

```php
$data = '{"data":"' . base64_encode($fileContents) . '"}'
```

2. less memory usage and faster when you base64 encoding with an external utility such as [base64](https://linux.die.net/man/1/base64). You can just work with files or use more advanced pipes with [`proc_open`](https://secure.php.net/manual/en/function.proc-open.php). I think this scenario only makes sense when you can do the base64 encoding ahead of time.

3. You can choose to use an alternative form of serialization format. The documentation [mentions](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html) you can use CBOR. I'm not sure if this would uses less memory while encoding though but worth a shot. Packagist mentions [three packages](https://packagist.org/search/?q=CBOR) for it at the time if writing. And also here you could use an external program if the PHP libs are not fast (after all php's base64_encode has a low level implementation in C, where as these CBOR libraries are 100% php).

Hope this helps!

**Comment by polyfractal** [comment]
Great points @flip111!
