### ISSUE TITLE
snapshot()->create() ignores custom index/indices parameter

### ISSUE THREAD

**Issue by videbligo-eng** [elastic/elasticsearch-php#416]
### Summary of problem or feature request

using custom fields in snapshot->create ignores index setting and snaps the whole cluster. Confirmed that delete does respect the same setting and works:

### Code snippet of problem

```
  $snap_params['repository']=$repository;
    $snap_params['snapshot']='snapshot_' . $yesterday;
    $snap_params['body']['wait_for_completion']=true;
    $snap_params['custom']['body']['index']=$yesterdays_index;

    $snapshot_result = false;
    try {
      $snapshot_result =  $client->snapshot()->create($snap_params);
    } catch (Exception $e) {
      echo 'No such snapshot exception: ',  $e->getMessage(), "\n";
    }
      if($snapshot_result) {
        return true;
      } else if ($e) {
        return false;
      }
```
The above code snippet snaps the entire cluster.

Changing this one line:
`$snapshot_result =  $client->snapshot()->create($snap_params);`
to 
`$snapshot_result =  $client->snapshot()->delete($snap_params);`

deletes only the index stated.

I tried 'index' and 'indices' and in both cases the results are as-is.
### System details

- Operating System - Ubuntu Trusty
- PHP Version 5.5.9
- ES-PHP client version ~2.0
- Elasticsearch version - 2.3

**Comment by videbligo-eng** [comment]
Hi, any thoughts on this or even a workaround? Using this 2.0 client is causing a significant problem for us since we snap to s3 and snapping the whole cluster every day is driving costs up. Thank you!

**Comment by polyfractal** [comment]
Hi, sorry for the delay.  Been a busy week :)

So you just want to snapshot certain indices?  That's goes into the request body, like the other parameters.  E.g. this snapshot API request:

```json
PUT /_snapshot/my_backup/snapshot_1
{
  "indices": "index_1,index_2",
  "ignore_unavailable": "true",
  "include_global_state": false
}
```

Translates to:

```php
$snap_params = [
  'repository' => 'my_backup',
  'snapshot' => 'snapshot_1',
  'body' => [
    'indices' => 'index_1,index_2',
    'ignore_unavailable' => true,
    'include_global_state' => false
  ]
];
$client->snapshot()->create($snap_params);
```

The `custom` optional parameter allows you to add custom, non-whitelisted query parameters to the URL (not the body).  It's mainly used for authentication tokens, session IDs, proxy tags, that sort of thing.  And it only exists because the Client whitelists URL parameters to help the user specify correct ones.

Nothing like that exists for the body, since we never validate the body. :)
