### ISSUE TITLE
Doc update potentially needed: #256 shows how to delete a document type, but this method is now deprecated

### ISSUE THREAD

**Issue by malteriesch** [elastic/elasticsearch-php#431]
### Summary of problem or feature request

I was looking for a way to delete a document type so I can re-index it with a new mapping. I came across #256 that showed me how to do it. Looking at the source I realised that it is now deprecated. What is the new way of doing it? I tried to find out and I saw some suggestions in #101 but they did not seem to have made it into the main code base. I think it would be useful to update the PhpDoc comment to point to the new way of achieving this.
### Code snippet of problem

File: src/Elasticsearch/Namespaces/IndicesNamespace.php, from Line 848:

``` php
/**
     * @deprecated
     * $params['index'] = (list) A comma-separated list of index names; use `_all` for all indices (Required)
     *        ['type']  = (string) The name of the document type to delete (Required)
     *
     * @param $params array Associative array of parameters
     *
     * @return array
     */
    public function deleteMapping($params)
    {
        $index = $this->extractArgument($params, 'index');

        $type = $this->extractArgument($params, 'type');

        /** @var callback $endpointBuilder */
        $endpointBuilder = $this->endpoints;

        /** @var \Elasticsearch\Endpoints\Indices\Mapping\Delete $endpoint */
        $endpoint = $endpointBuilder('Indices\Mapping\Delete');
        $endpoint->setIndex($index)
                 ->setType($type);
        $endpoint->setParams($params);
        $response = $endpoint->performRequest();

        return $endpoint->resultOrFuture($response);
    }
```
### System details

- Operating System
  All, tried on Ubuntu 14.04
- PHP Version
  All, tried on PHP 7
- ES-PHP client version
  v2.2.0
- Elasticsearch version
  2.3

**Comment by polyfractal** [comment]
Hm, yes, this is a tricky situation.

This functionality used to be powered by the Delete-By-Query API internal to ES.  The implementation was unsafe, so it was removed, then later re-introduced as a safer variant in a [Delete-By-Query plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugins-delete-by-query.html).

So the solution is to basically install the new plugin, and use a query that selects documents based on their `_type` field.

I'm currently working on better support for [registering custom namespaces](https://github.com/elastic/elasticsearch-php/commit/b1a27b70e928180230ae491736dece5d54cafaea), which is going to be used to implement pluggable namespaces for the Delete-By-Query plugin, X-Pack, etc.

So that's actively in progress, basically.

If you don't want to use the plugin, you can mimic it by doing a scroll search on `_type`, and issuing bulk deletes against the matched documents.  That's essentially what the plugin does internally.

**Comment by malteriesch** [comment]
Thanks for the quick response  :)

Erm, yes. I can see the problem here then...

Fair enough, I wanted to save myself from having to re-indexing all document types (to save on downtime), but I guess the way forward then [is to delete the index and use aliases to re-index all document types in the background without any downtime](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html)

The custom namespaces sound like a very nice addition.

**Comment by armetiz** [comment]
Hi @polyfractal 
If I want to use the [Delete-By-Query](https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/delete-by-query-usage.html) plugin with the PHP Library. How can I do it properly ?

Regards.

**Comment by ezimuel** [comment]
Outdates issue.
