### ISSUE TITLE
Uri in getURI from Elasticsearch\Endpoints\Template\Put is outdated

### ISSUE THREAD

**Issue by GabrielRondelli** [elastic/elasticsearch-php#436]
The uri is hardcoded and not in line with the official documentation, not even in the dev-master branch:

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

```php
 public function getURI()
    {
        if (isset($this->id) !== true) {
            throw new Exceptions\RuntimeException(
                'id is required for Put'
            );
        }

        $templateId = $this->id;
        $uri  = "/_search/template/$templateId"; //this should be /_template/$templateId;

        return $uri;
    }
```

- Operating System: Windows 7 Enterprise
- PHP Version: 5.6.5
- ES-PHP client version: dev-master
- Elasticsearch version: 2.3

**Comment by polyfractal** [comment]
Ah, no, there are just different types of templates / endpoints :)

Index templates are accessed through the [indices() namespace](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/IndicesNamespace.php#L522) and use the endpoint at [Endpoints\Indices\Template\Put](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Indices/Template/Put.php).  

E.g.
```php
$client->indices()->putTemplate([...]);
```

They are accessed through the `indices()` endpoint because it's an action that is being performed on one or more indices.  You'll find similar index-level APIs there (such as `stats()`, `snapshot()`, `putSettings()`, etc)

The templates you are looking at are the [Search Template API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html), which are located under the main [Client namespace](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Client.php#L1166).

E.g.
```php
$client->putTemplate([...]);
```

It is a little confusing, but alas, that's how the APIs are named in Elasticsearch.  Hope this helps!
