### ISSUE TITLE
ClientBuilder incorrectly preprends missing scheme 

### ISSUE THREAD

**Issue by steanjohn** [elastic/elasticsearch-php#442]
### Summary of problem or feature request
In certain situations a URL will have http:// incorrectly appended in the ClientBuilder->prependMissingScheme() function, which then causes parse_url() in ClientBuilder->extractURIParts() to return an array instead of false 
This is due to the password containing the char #
What I would expect is to receive an exception, so perhaps call parse_url() before prependMissingScheme()

### Code snippet of problem

```php
$host = "https://admin:password#@xyz.com:443"; // notice the # as the last char in the password, which is a valid password but breaks this api
. 
echo var_dump( extractURIParts( prependMissingScheme( $host ) ) ); 

/**
http://https://admin:password#@xyz.com:443
array(5) {
  ["scheme"]=>
  string(4) "http"
  ["host"]=>
  string(5) "https"
  ["path"]=>
  string(16) "//admin:password"
  ["fragment"]=>
  string(12) "@xyz.com:443"
  ["port"]=>
  int(9200)
}

**/

  function prependMissingScheme($host)  // copied from source
    {
        if (!filter_var($host, FILTER_VALIDATE_URL, FILTER_FLAG_SCHEME_REQUIRED)) {
            $host = 'http://' . $host; // this incorrectly prepends , which confuses parse_url
        }

       echo $host;
        return $host;
    }

    function extractURIParts($host) // copied from source
    {       
        $parts = parse_url($host); // this does not return false for http://https://admin:password#@xyz.com:443

        if ($parts === false) {
            throw new InvalidArgumentException("Could not parse URI");
        }

        if (isset($parts['port']) !== true) {
            $parts['port'] = 9200;
        }

        return $parts;
    }
```

### System details

- Operating System windows 10
- PHP Version 5.5.37
- ES-PHP client version "elasticsearch/elasticsearch" : "^2.2"
- Elasticsearch version irrelevant as this fails before getting to ES

**Comment by polyfractal** [comment]
Been poking at this a while, it's turned out to be a relatively tricky pickle. 

Fixing the prepending problem was straightforward, but the larger issue is that `parse_url()` barfs on the # sign in the password regardless.  Basically, the pound sign is valid since unicode characters are encoded to base64 for HTTP basic auth.  But `parse_url()` seems to assume that is part of the URI fragment.  Since it's in the wrong place, it blows up.

This particular quirk can be overcome by appending a trailing slash automatically if it's missing.  But there are similar, related issues such as including an "@" sign in the password.  

I think `parse_url()` just needs to be thrown out.  I'm investigating other solutions right now, notably [Leage/URI](http://uri.thephpleague.com/).  But that requires ext-intl, which may constitute as a bwc break.  

Still investigating, will let you know as I progress.

## Alternative syntax

I could also provide a backup syntax which allows you to specify user/pass separately:

```php
$hosts = [
  [
    'host' => 'foo.com'
    'user' => 'abc',
    'pass' => 'xyz#$!)(#$@'
  ]
]
```

Given all the problems that this part of the code has generated (related: #461, https://github.com/elastic/elasticsearch-php/issues/376#issuecomment-172593919), I'm seriously tempted to make the host initialization 100% explicit in 5.x.  No magic auto-detection of scheme, no extracting the user/pass from an inline string, etc.  

There are too many variations of how user/pass/domain/host can be constructed for a magic solution to work, it seems.

**Comment by polyfractal** [comment]
Closing, since I think the extended syntax solves this problem...sorta.  A longer-term fix will have to wait for the next major version, or perhaps never.  Not entirely sure this is solvable easily, and the extended syntax does it easily enough.

Thanks for the report!
