### ISSUE TITLE
Get error details in ping() method

### ISSUE THREAD

**Issue by Programie** [elastic/elasticsearch-php#448]
### Summary of problem or feature request

I would like to get some details about an error on a call to the ping() method. Maybe throwing an exception instead of catching it in the ping() method would be useful. So the method would never return something but throws an exception on error.

### Code snippet of problem

```php
try {
   $client->ping();
} catch (Exception $exception) {
   $message = $exception->getMessage();
   // Do something with $message
}
```

### System details

- ES-PHP client version: v2.2.1

**Comment by polyfractal** [comment]
Hey, sorry for the delay in responding. 

I'm not so sure about this... the point of the ping is to provide a simple yes/no binary result.  It's predominantly used by the sniffing feature to get a quick handle on a node's availability, and in this context we don't want to deal with errors. We just want a simple yes/no decision.  It's also used by other people for monitoring purposes.

I'd recommend you just use the [Info endpoint](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Client.php#L107), since it hits the same [ES API](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Info.php#L21) as the [Ping endpoint](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Ping.php#L21).  The Ping endpoint is really just the Info endpoint with a true/false wrapper around it :)

**Comment by Programie** [comment]
OK, then I could just use the info() method and catch any exception to get more details about the failure.

In my case I also want it for monitoring purposes, but I want a bit more details instead of a simple OK or error status.

Thanks for your help! :)

**Comment by polyfractal** [comment]
Np, happy to help! :)
