### ISSUE TITLE
Get final request url?

### ISSUE THREAD

**Issue by patrick-radius** [elastic/elasticsearch-php#45]
Hi,
is there a way to retrieve the final url that is generated and used to query ES?
I think this can be very useful for unit testing and debugging.

Thanks

**Comment by PabloBorda** [comment]
fuck

**Comment by IllyaMoskvin** [comment]
We are currently using [cviebrock/laravel-elasticsearch](https://github.com/cviebrock/laravel-elasticsearch). Because it presents a facade to the Elasticsearch client, it wasn't immediately obvious how @polyfractal's example should be translated to work within that environment. This thread shows up high in Google, so I'd like to share our solution:

```
// Get to `transport` through the facade's `connection` static method
$last = Elasticsearch::connection('default')->transport->lastConnection->getLastRequestInfo();

// Just the body (JSON string)
$body = $last['request']['body'];

// If you are inside a controller, this is prettier than dd()
return response()->json( json_decode( $body ) );
```

Equivalent one-liner:

```
return response()->json( json_decode( Elasticsearch::connection('default')->transport->lastConnection->getLastRequestInfo()['request']['body'] ) );
```

Hopefully this'll save some folks the `dd()` calls to figure it out.

**Comment by hrvoj3e** [comment]
Is this still a thing?
Is there a way to do this in version 8 ?
