### ISSUE TITLE
Not sure if bottlenecked by hardware of if I did something wrong here.

### ISSUE THREAD

**Issue by stugmi** [elastic/elasticsearch-php#463]
### Summary of problem or feature request

I'm trying to a search with wildcard on an elasticsearch index with 500,000,000 results.
Example search would be: query=*_user_post

```
exception 'Elasticsearch\Common\Exceptions\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51
Stack trace:
#0 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection()
#1 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\Transport->getConnection()
#2 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(230): Elasticsearch\Transport->performRequest()
#3 /var/www/XXXXXXX/vendor/react/promise/src/FulfilledPromise.php(25): Closure$Elasticsearch\Connections\Connection::wrapHandler()
#4 /var/www/XXXXXXX/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then()
#5 /var/www/XXXXXXX/vendor/guzzlehttp/ringphp/src/Core.php(344): GuzzleHttp\Ring\Future\CompletedFutureValue->then()
#6 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(283): GuzzleHttp\Ring\Core::proxy()
#7 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(159): Closure$Elasticsearch\Connections\Connection::wrapHandler#2()
#8 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(106): Elasticsearch\Connections\Connection->performRequest()
#9 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Endpoints/AbstractEndpoint.php(80): Elasticsearch\Transport->performRequest()
#10 /var/www/XXXXXXX/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php(1091): Elasticsearch\Endpoints\AbstractEndpoint->performRequest()
#11 /var/www/XXXXXXX/panel/index.php(207): Elasticsearch\Client->search()
#12 /var/www/XXXXXXX/panel/index.php(336): DBsearch()
#13 {main}
```

### Code snippet of problem
```php


        $params = [
            'size' => 200,
            'index' => 'posts',
            'body' => [
                'query' => [
                    'bool' => [
                        'filter' => [
                            'wildcard' => [$t => strtolower($q)], // t is type and q is the query f.eks *_posts_ID
                        ],
                    ],
                ],
            ],
        ];

    $response = $client->search($params);
```
It does work fine for smaller queries but once I try using wildcard it fails.
Trying to figure out if its something wrong on my side or if I have to create multiple nodes to handle this much data on one dedicated server.

### System details

- Operating System / Ubuntu 14.04.
- PHP Version / HHVM 3.15.0
- ES-PHP client version / 2.0
- Elasticsearch version  / 2.4.0

Server specs:
8GB ram
4 Core Intel Xeon (all it tells me)
And enough space.

**Comment by polyfractal** [comment]
It's likely that you knocked the node over.  Querying 500m docs with a suffix wildcard like that is pretty expensive.

It either timed out while executing the query (and so the client marked the node as dead), or the server itself started doing something like heavy GC's which caused the query to time out (and thus the client marked it as dead).

You might try a longer timeout, by adding it to your $params:

```php
 $params = [
            'size' => 200,
            'index' => 'posts',
            'body' => [
                'query' => [
                    'bool' => [
                        'filter' => [
                            'wildcard' => [$t => strtolower($q)], // t is type and q is the query f.eks *_posts_ID
                        ],
                    ],
                ],
            ],
            'client' => [
                'timeout' => 300   // <----- here
            ]
        ];

    $response = $client->search($params);
```

You should also check your server logs for long GC warnings, which are an indicator that your node is unhappy.  You should probably also keep an eye on heap utilization (it should be below 75% for a happy node), and watch CPU util too.

Generally, wildcards in that format -- a suffix wildcard -- are discouraged.  Looking for `"*_user_post"` defeats Elasticsearch's index data structure, since the starting wildcard means it needs to essentially do a linear scan over all term.

If you need this kind of pattern often, you can setup a secondary "suffix" analysis chain where you use the [Reverse Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-reverse-tokenfilter.html), then query that with a [match_phrase_prefix](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-phrase-prefix) or [prefix query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html)

For example, the query `"*_user_post"` will first be reversed: `"tsop_resu_"`

Then it's executed as a prefix search: `"tsop_resu_*"`, which is considerably faster, since the long prefix allows the index datastructure to efficiently skip most of the terms.

**Comment by stugmi** [comment]
I haven't quite caught onto the analyzers and such, but would I have to recreate the index of change settings of it?
Or can this be done in the $params?

Also, thanks for the fast reply.

**Comment by polyfractal** [comment]
Yep, that's correct.  You'd have to reindex your data with the new "reverse" analyzer.  It's basically changing what tokens are stored in the inverted index, which requires reindexing all the original data so that the new tokens can be processed/created.
