### ISSUE TITLE
FutureArray in GuzzleHttp does not work

### ISSUE THREAD

**Issue by BingBingGood** [elastic/elasticsearch-php#467]
First of all my situation is a little special.
Namely i want to use elasticsearch-php which needs PHP 5.4, but i have limitation that i can only use PHP 5.3.17.
The OS is Ubuntu 14.04.2 LTS.
So i want to use elasticsearch-php 2.0 with elasticsearch 2.4(but the default elasticsearch built through composer of elasticsearch-php is 2.2.1).
I convert the whole elasticsearch-php 2.0 to 5.3 with tools, but e.g. some "callable" which is type hint of 5.4 can not be converted automatically.
So i got problem directly by calling
$clientBuilder = Elasticsearch\ClientBuilder::create()->build();
It expects callable.
As try i delete some relavant callable from the source code of GuzzleHttp.
But then it complains that FutureArray does not implement the interface method wait, cancel, promise, then etc.
It actually really does not implements them.

I do not understand this.
So my questions are
1. Can i use  elasticsearch-php 2.0 with elasticsearch 2.4 AND PHP 5.3.17?
2. Is GuzzleHttp stable? Why FutureArray does not implement needed methods?
3. I have tried to call "curl" query directly in the code, and it works.
So i can just use "curl" query with PHP 5.3.17? Is there performance issue if i use "curl" query directly?

Thanks!

**Comment by polyfractal** [comment]
`FutureArray` uses a trait called [MagicFutureTrait](https://github.com/guzzle/RingPHP/blob/master/src/Future/FutureArray.php#L9), which uses a trait called [BaseFutureTrait](https://github.com/guzzle/RingPHP/blob/master/src/Future/MagicFutureTrait.php#L13), which has the various methods like [wait()](https://github.com/guzzle/RingPHP/blob/master/src/Future/BaseFutureTrait.php#L50), cancel(), etc

> Can i use elasticsearch-php 2.0 with elasticsearch 2.4 AND PHP 5.3.17?

Not officially, without heavy modification.  The 2.0 branch uses features that are only available after 5.3.  And 5.3 was EOL'd over two years ago.  There's no good reason to support it anymore... you should really upgrade :)

> Is GuzzleHttp stable? Why FutureArray does not implement needed methods?

See above comments.  The various Guzzle bits are coming from RingPHP.

> I have tried to call "curl" query directly in the code, and it works.
So i can just use "curl" query with PHP 5.3.17? Is there performance issue if i use "curl" query directly?

The FutureArray things allow the usage of curl's multi_select behavior, to batch multiple calls into one call to curl (so that curl can run them in parallel).  The underlying functionality is just curl though, so performance will be roughly equivalent.

There are some performance differences between the multi-interface and the easy ("single") interface, but not enough to care about in most cases.

**Comment by BingBingGood** [comment]
Thanks man! Now i know what i should do!

**Comment by polyfractal** [comment]
Happy to help :)  Closing, feel free to reopen if you have more questions/problems!
