### ISSUE TITLE
"No alive nodes found in your cluster" with v2.2.1, Laravel Scout, AWS Elasticsearch Service

### ISSUE THREAD

**Issue by hughgrigg** [elastic/elasticsearch-php#477]
I've hit the following problem and have not been able to find a solution.

All Laravel Scout interactions with ElasticSearch get the "No alive nodes found in your cluster" exception (e.g. when running the Laravel Scout `php artisan scout:import` command).

I'm getting the exception from `elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51`.

This is with an AWS Elasticsearch Service host.

From debugging, elasticsearch-php definitely has the right scheme, host and port. 

On the machine in question, I can curl the Elasticsearch host from the command line on 80 and 443 without issues. I can also access it successfully with Guzzle and with curl functions in PHP. So it doesn't appear to be firewall, AWS config etc.

It does work fine on the development machine with a local instance of Elasticsearch.

Any ideas for what else I could look at?

### System details

- PHP 7.0.12-1+deb.sury.org~trusty+1
- Ubuntu 14.04.5 LTS
- elasticsearch-php v2.2.1
- Elasticsearch 2.3 on AWS Elasticsearch Service

**Comment by polyfractal** [comment]
Hm, can you post your config for Laravel Scout, the complete exception, and any relevant code from your app?

You could also try [enable logging](https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_configuration.html#enabling_logger) and see if anything useful shows up

I'm not super familiar with Laravel Scout, but that exception generally means one of two things:

1) Your nodes/cluster are actually down, but as you said, this is likely not the case since you can access it from other methods
2) Configuration error, which means the client just bombs out early because the configured host is not reachable

Does your AWS password have a hash, question-mark or some other special characters?  There are some known issues with PHP's "inline" url parsing with special characters.  This can cause the parsed URL to be totally incorrect, which ultimately means the host fails to connect.

I just tagged `v2.2.2` which [includes an "extended" hosts syntax](https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_configuration.html#_extended_host_configuration), which allows more flexible / less error-prone configuration of the host.  I'd give that a shot and see if it helps too.

**Comment by hughgrigg** [comment]
Thanks, was able to get it working with `v2.2.2`, although not sure exactly why as I believe I was supplying the right scheme and port previously. Anyway thanks for your help.

**Comment by polyfractal** [comment]
Huh... strange, I'm not sure why that worked.  But a fix is a fix, I won't complain :)
