### ISSUE TITLE
No alive nodes found in your cluster in v5.0

### ISSUE THREAD

**Issue by zmf0507** [elastic/elasticsearch-php#519]
### Summary of problem or feature request

I am using the search feature of elastic search but this error is coming out while running my files on localhost.

my configuration code:

 use Elasticsearch\ClientBuilder;

require 'vendor/autoload.php';
$client = Elasticsearch\ClientBuilder::create()->build();

the error while sending a query for search : 

Fatal error: Uncaught Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in C:\xampp\htdocs\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php:51 Stack trace: #0 C:\xampp\htdocs\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(72): Elasticsearch\ConnectionPool\StaticNoPingConnectionPool->nextConnection() #1 C:\xampp\htdocs\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Transport.php(90): Elasticsearch\Transport->getConnection() #2 C:\xampp\htdocs\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\Connections\Connection.php(227): Elasticsearch\Transport->performRequest('GET', '/1/books/_searc...', Array, '{"query":{"matc...', Array) #3 C:\xampp\htdocs\elastic\vendor\react\promise\src\FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array) #4 C:\xampp\htdocs\elastic\vendor\guzzlehttp\ringphp\src\Future\CompletedFutureValue.ph in C:\xampp\htdocs\elastic\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php on line 51

please help me fix this problem. I am using localhost through XAMPP.

- Operating System - windows
- PHP Version - 7
- ES-PHP client version - v5.0
- Elasticsearch version - v5.0

**Comment by zmf0507** [comment]
I tried running a curl query for search in my windows git bash and this error came in.

CURL QUERY : 

curl -XGET 'localhost:9200/my_index/my_type/_search' -d '{
    "query" : {
        "match" : {
            "testField" : "abc"
        }
    }
}' 

ERROR : 

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to localhost port 9200: Connection refused

Please check

**Comment by zmf0507** [comment]
No reply..please can you help me fix it quickly
I am waiting

**Comment by polyfractal** [comment]
It looks like your node isn't running.  The curl request should return with a response, but since it's also being refused, that indicates the server isn't running.

You should read through the E[lasticsearch "Getting Started" documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html) for some more information on getting the server running.

**Comment by pmaselkowski** [comment]
Also check Sense extension to try elasticsearch https://chrome.google.com/webstore/detail/sense-beta/lhjgkmllcaadmopgmanpapmpjgmfcfig

**Comment by deepakkakran** [comment]
Im also getting the same error when try to connect with the client, but works fine through postman.

**Comment by zmf0507** [comment]
now its working fine through browser  but not through configured php file..plz help

**Comment by asabanovic** [comment]
For me, I am running elasticsearch 5 on homestead with vagrant. I get it up and listening on localhost:9200 and it works fine for some time (about 30 minutes maybe) and then suddenly in the middle of testing of my app, it stops working, coming back with this error. 

Any ideas ?

**Comment by polyfractal** [comment]
It's likely that the node either died, or stopped responding due to something like a long GC.  Check your Elasticsearch logs to see if there is anything interesting in there?  Small nodes being subjected to heavy usage can hit long GCs and potentially become nonresponsive temporarily.

From the client's perspective, the exception is very simple: it tried to send a request to the cluster, failed because of some transport/network-related failure, attempted it's configured retries then gave up.  It's almost always the cluster being unavailable, or sometimes SSL configuration problems.

**Comment by antonydandrea** [comment]
I am getting the same error with just the search function. Index works fine and it works fine on sense even after this error appears.

**Comment by addione** [comment]
try making changes in ClientBuilder.php 
check if default host is proper
you'll find here ES_HOME/src/Elasticsearch/ClientBuilder.php
near line#630

**Comment by polyfractal** [comment]
@addione It'd be easier to just supply a host when building the client, no?

**Comment by addione** [comment]
@polyfractal  yes obviosly but in some cases it was throwing "Segmentation Fault" so i just changed the default host to my elasticsearch endpoint

**Comment by Emn1ty** [comment]
I am also getting this issue but only when trying to connect to an Elastic Cloud free instance. Manual curl requests work fine, but when trying to create an index with this library I get the `NoNodesAvailableException`.

**Comment by polyfractal** [comment]
@Emn1ty Are you using HTTP or HTTPS?  E.g. HTTP is on 9200, but HTTPS is on port 9243 or 443 so you'll have to set those. Are you including your authentication user/pass?

Could you paste your initialization code?

**Comment by Emn1ty** [comment]
@polyfractal - I have tried both HTTP and HTTPS. Tried both port 9234 and 443 for HTTPS, have not tried 9200 for HTTP (though tried 80). I'll test that. Debugging shows that auth throws the proper authentication exceptions when it's not included so auth is working properly.

```php
// single line configs tried:
$hosts = [
    // throws proper auth exception
    'https://my-server.us-west-1.aws.found.io:9234',

    // all throw no nodes alive exception
    'https://username:password@my-server.us-west-1.aws.found.io:9234',
    'https://username:password@my-server.us-west-1.aws.found.io:443',
    'http://my-server.us-west-1.aws.found.io:80',
    'http://my-server.us-west-1.aws.found.io:9200',
];

$hosts = [
    // also throws no nodes alive exception
    [
        'host' => 'my-server.us-west-1.aws.found.io',
        'port' => 9234,
        'scheme' => 'https',
        'user' => 'username',
        'pass' => 'password'
    ]
];

$elasticsearch = Elasticsearch\ClientBuilder::create()->setHosts($hosts)
                                                      ->build();
```

**Comment by polyfractal** [comment]
Hm.  I just tried this with my free instance of Elastic cloud:

```php
$hosts = [
    'https://elastic:password@c89f5baf0da69a7fe6a70894d091c17e.us-east-1.aws.found.io:9243/'
];

$elasticsearch = Elasticsearch\ClientBuilder::create()->setHosts($hosts)
    ->build();

$results = $elasticsearch->search([]);
print_r($results);
```
and it returned a set of search results.  The longform version works too:

```
$hosts = [
    [
        'host' => 'c89f5baf0da69a7fe6a70894d091c17e.us-east-1.aws.found.io',
        'port' => 9243,
        'scheme' => 'https',
        'user' => 'elastic',
        'pass' => 'password'
    ]
];
```

Does the NoNodes exception happen immediately on your first API call, or after several API calls?
 Is your cluster somewhat loaded?  It may be possible that your node is hitting a GC, taking a while to respond and so the client thinks it has died.

If that happens, and you only have one node, the node is marked dead and subsequent calls will fail until the dead-timer expires.  You could try using the "simple" connection pool which doesn't track node liveness:

```php
$client = ClientBuilder::create()
            ->setConnectionPool('\Elasticsearch\ConnectionPool\SimpleConnectionPool', [])
            ->build();
```

Then, if one of the APIs fails due to a transient hiccup, the next API call will be unaffected.  It doesn't solve the underlying issue with the server, but will let you handle failures a bit more gracefully in that situation.

**Comment by Emn1ty** [comment]
@polyfractal - As I am connecting and when I call $client->indices()->index($params).

Trying the simple connection pool I am getting a more descriptive error now (`MaxRetriesException`). I'll take a look into this further and provide any updates I can after doing some more research.

**Comment by Emn1ty** [comment]
@polyfractal - So with some troubleshooting I found that the port was incorrect [ 9234 -> 9243 ]. However, a different issue has arisen (`PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\ServerErrorResponseException: {"ok":false,"message":"Unable to connect to the server."}` but my index still gets created) though I'm not sure it's relevant to this particular topic. I think what's going on here is NoNodesAlive is being thrown in arbitrary spots which makes things confusing. Everything appears to connect but in fact it's not connecting at all.

**Comment by polyfractal** [comment]
Would it be possible to paste a large section of your code so I can try to recreate it?  E.g. `$client->indices()->index([...])` is not an endpoint that exists (there's no index method in the indices namespace), so I'm not entirely sure what's going on.

I'm also not sure about that error message (`"Unable to connect to the server."`) since it isn't a response from Elasticsearch.  Are you going through a proxy?  Perhaps it's a response from Elastic Cloud's proxy layer or something.

The NoNodesAvailableException is pretty straightforward really: it basically means that all retries on all available nodes have been exhausted, and there are no more available nodes to try.  The exception isn't thrown for the SimpleConnection pool because it doesn't track "liveness" of nodes, so it just fails with a retry error instead.

**Comment by Emn1ty** [comment]
Well it is now working with Elastica (a library built on top of this one), so I'm pretty sure this has to do with how I've set it up and not something to do with this library. 

As for the syntax, got this from the [Elasticsearch PHP documentation](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_index_management_operations.html).

```php
$client = ClientBuilder::create()->build();
$params = [
    'index' => 'my_index'
];

// Create the index
$response = $client->indices()->create($params);
```

**Comment by polyfractal** [comment]
Ah, create.  Gotcha :)

I'll run a few more tests on my side and see if I can figure out what's going on. :)

**Comment by Emn1ty** [comment]
Yeah, I just realized my typo there. My apologies.

**Comment by polyfractal** [comment]
I'm going to close this ticket as it has meandered through several different problems.

@Emn1ty if you're still having issues, please feel free to open a new ticket with your current situation and we can go from there.  As it stands, I never discovered anything on my end so I'm still not sure what was going on :(

**Comment by borys-p** [comment]
In my case it was the VM update that switched the network stack to IPv6. This resulted in `localhost` being resolved to `::1` and my Elastic does not listen on that address. The fix is pretty simple, just setting `'http://127.0.0.1:9200'` as the primary host.

**Comment by Megabite1997** [comment]
Excuse me, @borys-p , how can I set 'http://127.0.0.1:9200' as the primary host.
