### ISSUE TITLE
No json 1.3.7 in Debian stable (jessie)

### ISSUE THREAD

**Issue by clem-compilatio** [elastic/elasticsearch-php#529]
### Summary of problem or feature request

Hello, documentation says it _"requires the native JSON extension to be version **1.3.7** or higher"_.

In debian stable, [php5-json](https://packages.debian.org/en/jessie/php5-json) **v1.3.6** is provided.
and this package is a direct dependency of [php5-cli](https://packages.debian.org/en/jessie/php5-cli).

The unstable [php5-json](https://packages.debian.org/en/sid/php5-json) is also in v1.3.6 (as of today), and even if it was in a newer version, it would not be suitable for a production environment.

So, I cant see how to meet this v1.3.7 requirement.

### System details

- Operating System : Debian 8 "jessie"
- PHP Version : 5.6.29
- ES-PHP client version : 5.0
- Elasticsearch version : 5.1.1

**Comment by polyfractal** [comment]
Can you upgrade to a newer version of PHP?  [PHP 5.6 is EOL](https://secure.php.net/supported-versions.php) which is one of the reasons why I felt comfortable making this a requirement.

The version of `ext-json` is important because we are now using `JSON_PRESERVE_ZERO_FRACTION`, which is a flag that's fairly critical in making sure that fields are typed correctly.  PHP's propensity for dropping zero fractional values without that flag means Elasticsearch will see some doubles (`0.0`) as longs (`0`) and map them incorrectly.

If you really can't update your machines (you should!), you can set a manual override for `ext-json` using the [`platform`](https://getcomposer.org/doc/06-config.md#platform) Composer config option.  Alternatively, you could use `--ignore-platform-reqs` when installing.  Both of those will satisfy Composer's version constraint.

Then, you'll need to create your own serializer which doesn't use the constant:

```php
class MyCustomSerializer extends \Elasticsearch\Serializers\SmartSerializer implements \Elasticsearch\Serializers\SerializerInterface
{

    /**
     * Serialize assoc array into JSON string
     *
     * @param string|array $data Assoc array to encode into JSON
     *
     * @return string
     */
    public function serialize($data)
    {
        if (is_string($data) === true) {
            return $data;
        } 

        $data = json_encode($data);  // Do not use JSON_PRESERVE_ZERO_FRACTION here
        if ($data === '[]') {
            return '{}';
        }
        return $data;
    }
}
```

And plug it in:

```php
$mySerializer = new MyCustomSerializer();

$client = ClientBuilder::create()
            ->setSerializer($mySerializer)
            //... any other options you normally set
            ->build();
```

*Note: all the above untested*

**Comment by clem-compilatio** [comment]
I switched to `Ubuntu 16.04 LTS` which provides `ext-json 1.4.0` (and php 7).

**Comment by madhancock** [comment]
@polyfractal Although closed I thought I'd note a couple things here:

PHP 5.6 is not EOL. EOL for PHP 5.6 is Jan 2019.

Enterprise users running the latest Debian will not be able to update their packages as `ext-json` will never be upgraded in the latest release (Jessie). Debian is used for package and security stability for exactly this reason.

The `unstable` repo for Debian goes into the next release, which as yet has no release date. Until then Debian users will have to insert that shim script.

I have to assume that there's a technical reason why that shim could not have been part of the ES client codebase. This will present a problem for my team. It is unfortunate.

Thanks for at least providing some solutions, however for us a better solution may in the end be to drop the plugin in core code and write something around it.

**Comment by polyfractal** [comment]
PHP 5.6 was EOL for active support in Jan 2017, and security support is EOL in Dec 2018:

![image](https://cloud.githubusercontent.com/assets/1224228/25007896/fba0af12-202f-11e7-8322-722d29991ee6.png)


However, I relented on this issue because I realized it'll be a huge pain for Debian users who are stuck with the version shipped with their release.  See this [issue/comment for more details](https://github.com/elastic/elasticsearch-php/issues/534#issuecomment-277246228).  Basically, you can do this if you're stuck on PHP 5.6 with an incompatible `json-ext`:

```php
$client = ClientBuilder::create()           
                    ->setHosts($hosts)
                    ->allowBadJSONSerialization() // Allow bad versions of json-ext
                    ->build();   
```

You'll need to use `v5.1.3` or later to get this fix.  Do note that this leaves you suceptible to the bug that we were trying to fix, namely that Elasticsearch may dynamically map floats incorrectly if the first document it see's is something like `10.0`, `15.0`, etc.  So be careful to either map those fields explicitly, or disable dynamic mapping entirely.

Let me know if you have any questions! :)

**Comment by madhancock** [comment]
PHP's definition for product states indicate that 5.6 is not EOL.

![image](https://cloud.githubusercontent.com/assets/2341980/25009154/aa19d370-205d-11e7-8b46-70983a4eb2c5.png)

The product is still alive until security support has ended.

RIP enterprise users stuck on RHEL 5.4 :)

Again, appreciate the additional workaround. I'm hoping Deb 9 rolls out soon with PHP 7 support.
