### ISSUE TITLE
Increased response time on guzzle update

### ISSUE THREAD

**Issue by saishsali** [elastic/elasticsearch-php#558]
### Summary of problem or feature request
I'm using guzzle HTTP/guzzle bundle version 5.3.0 and elasticsearch-php bundle version 5.3.1 in project. On updating the guzzle bundle to version 6.2.3, the response time of the search being done using elastic search increases significantly (from 13 ms to 170 ms). What could be the reason behind the increase in response time?

### System details
- Operating System: Ubuntu
- PHP Version : 7.0.4
- ES-PHP client version : 5.3.1 
- Elasticsearch version : Amazon elasticsearch (https://aws.amazon.com/elasticsearch-service/)

**Comment by polyfractal** [comment]
Hm, I think it's probably unrelated?  ES-PHP actually uses [https://github.com/elastic/elasticsearch-php/blob/master/composer.json#L16](Guzzle/RingPHP), not the main guzzle package.  So I don't think updating Guzzle would affect anything.

We're also pinned to the 1.x branch of RingPHP, and because Guzzle no longer uses RingPHP, it doesn't really see any development and is pretty stable

**Comment by saishsali** [comment]
@polyfractal : Thanks! I'm using guzzlehttp/ringphp version 1.1.0. Every time I update Guzzle, response time increases. Any idea what might be the issue? I'm updating to guzzle version 6.2.3 because of security issue

**Comment by polyfractal** [comment]
I'm unsure tbh.  It really should affect ES-PHP and vice versa.

Perhaps the newly generated autoloader is slower because it is larger, which will cause all PHP class loading to slow down?  That's one of the reasons ES uses RingPHP instead of the main Guzzle package: to cut down on autoloader slowdowns.

Or perhaps it's a caching issue, where your OS cache is thrashing more?  Or the PHP 7 opcode cache is thrashing? 

Not sure, I think you may have to break out a profiler to dig into this one.

**Comment by ezimuel** [comment]
Outdated issue.
