### ISSUE TITLE
Unable to catch the Exceptions thrown by Elasticsearch client

### ISSUE THREAD

**Issue by LuisMejiaF** [elastic/elasticsearch-php#571]
This happens with various exceptions. A couple of days ago it happened with the `Elasticsearch\Common\Exceptions\Forbidden403Exception`, I have a try-catch in my code and the exception was not caught.

I just tried this to make another type of test: 
```php
$client_config = [
    'hosts' => [
        'https://url_host_that_does_not_exists'
    ],
    'retries' => 0
];

try {
    $client = ClientBuilder::fromConfig($client_config);
} catch (Elasticsearch\Common\Exceptions\MaxRetriesException $e) {
    die('Please be gentle');
}
```

But the exception is not caught by the catch :/, I still receive:
> Fatal error: Uncaught Elasticsearch\Common\Exceptions\MaxRetriesException: cURL error 6: Could not resolve host....

### System details
- **Operating System:** Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-38-generic x86_64)
- **PHP Version:** 7.0.8
- **ES-PHP client version:** 2.3.0
- **Elasticsearch version:** 2.3.2

**Comment by metfan** [comment]
Did you forget '\' at start of exception's class namespace?

**Comment by LuisMejiaF** [comment]
Sorry, I don't understand what you mean with this: 
> Did you forget '' at start of exception's class namespace?

But anyways. I have more input to add here to this. I did another test and noticed that the `MaxRetriesException` is only thrown until I execute one of the endpoints. I guess this is the intended behavior, because you don't want to initiate a connection until is actually used.

The problem is this:
```php
try {
    $client_config = [
        'hosts' => [
            'https://url_host_that_does_not_exists'
        ],
        'retries' => 0
    ];

    $client = Elasticsearch\ClientBuilder::fromConfig($client_config);

} catch (Exception $e) {
    /* 'This exception is never caught'); */
}
/**** Later in the execute, most likely in other file, depending of the framework ****/
try {
    $client->get([
        'id' => 'sdkfjklsd',
        'index' => 'this_index_dont_exists',
        'type' => 'neither_this'
    ]);
} catch (Exception $e) {
    /* This exception is thrown and caught */
    print 'Exception: ' . get_class($e) . '<br>';
    print 'Message: ' . $e->getMessage() . '<br>';
    
    //output
    /*
     * Exception: Elasticsearch\Common\Exceptions\Curl\CouldNotResolveHostException
     * Message: cURL error 6: Could not resolve host: https
     */
}
```
My point is, that I would like to catch the exception  `Elasticsearch\Common\Exceptions\Curl\CouldNotResolveHostException`  when I'm creating the Client, not when I'm calling endpoints.

**Comment by polyfractal** [comment]
Sorry for delay in getting to this ticket.

You're correct, none of the connection pools actively try to connect to nodes until an API endpoint is invoked.  That's largely by design, since a client may be instantiated many times and not actually used. Or instantiated but only used for a single API call and you don't want it pinging a dozen nodes for just one API.

If you want that behavior, I think you're best off writing a [Custom ConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_connection_pool.html#_custom_connection_pool) that pings all the nodes in the constructor, which will happen as soon as the ClientBuilder instantiates the ConnectionPool and before the Client is even built.

**Comment by LuisMejiaF** [comment]
Thanks for the input.

Well, I will work on the custom connection pool then. Thanks for the link.

Closing this.
