### ISSUE TITLE
delete type

### ISSUE THREAD

**Issue by githubyyf** [elastic/elasticsearch-php#586]
hi,
I have some problems that need help，I want to delete（or empty data） index=shops&type=targetShops, I don't know what to do。
elasticsearch = 5.2.1

![image](https://cloud.githubusercontent.com/assets/21100974/26388959/ec692f22-4089-11e7-8ed6-c99b9879dace.png)

thank you

**Comment by polyfractal** [comment]
It is no longer possible to delete an entire type in Elasticsearch. See the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/5.4/indices-delete-mapping.html

You can run a DeleteByQuery to remove all the documents you don't want, but that will leave the mapping in place since they cannot be deleted anymore.  Alternatively, you'll need to create a new index with the mapping you want and reindex into that.
