### ISSUE TITLE
Alphabetically sorting is not working

### ISSUE THREAD

**Issue by mrverak** [elastic/elasticsearch-php#608]
###  Mapping here

```
'city_name' => array(
				'type' => 'text',
				'fields' => array(
					'raw' => array(
						'type' => 'keyword'
					)
				)
			)
```

### Query is here 
```
[sort] => Array
        (
            [0] => Array
                (
                    [city_name.raw] => asc
                )

        )
```
### What i am getting is here

So data array coming empty, i stuck here.

**Comment by polyfractal** [comment]
Can you paste your full query?  Are you sure it's the sort, and not the query that is returning zero results?  What happens if you omit the sort?

**Comment by mrverak** [comment]
Dear polyfractal

Thanks for contacting me, actually it seem that i am not able to update mapping.

Old field mapping:
'city_name' => array(
				'type' => 'string',
				'analyzer' => 'standard'
			)
Below is updates to field
'city_name' => array(
				'type' => 'string',
				'fields' => array(
					'raw' => array(
						'type' => 'keyword'
					)
				)
			)

The problem is when i getMappings it don't display any changes in mapping, giving me old one.
Do do think this is the problem?

**Comment by mrverak** [comment]
I actually re indexing all the data. this is happpening when we do data release.
first i dropping the index like below

```
public function drop()
	{
		$params = array(
			'index' => $this->index,
			'client' => array('ignore' => array(404,400,500))
		);
		return $this->client->indices()->delete($params);
	}
```

After that creating index freshly with the function below

```
public function create()
	{
		$mappings = array();
		$mappings[$this->type] = $this->mapping;
		$params = array(
			'index' => $this->index,
			'body' => array(
				'mappings' => $mappings
			),
			'client' => array('ignore' => array(404,400,500))
		);
		return $this->client->indices()->create($params);
	}
```

Then after that insert function called for a lot of data.
I think ES should re create all indexes and mapping, am i right?

**Comment by mrverak** [comment]
**Here is my Query**
```
Array
(
    [query] => 
    [filters] => Array
        (
            [country] => de
            [degree] => Array
                (
                    [or] => Array
                        (
                            [0] => 1
                            [1] => 2
                            [2] => 3
                            [3] => 4
                        )

                )

        )

    [size] => 5
    [from] => 0
    [sort] => Array
        (
            [0] => Array
                (
                    [city_name.raw] => asc
                )

        )

    [function_score] => Array
        (
            [boost_mode] => sum
            [functions] => Array
                (
                    [0] => Array
                        (
                            [script_score] => Array
                                (
                                    [script] => doc['featured'].value * 0.05
                                )

                        )

                )

        )

)
```

**Comment by mrverak** [comment]
Any body here?

**Comment by polyfractal** [comment]
I think you may have better luck asking at the [Elasticsearch Discussion Forums](https://discuss.elastic.co/), since this doesn't really appear to be a bug with the PHP client.

It sounds like your PutMappings call is not working correctly, you should check the exception or error that Elasticsearch is returning.  It's likely a syntax error.  

If the mapping isn't being updated, the field won't exist to sort on, which would explain your missing results.

You probably shouldn't have `'client' => array('ignore' => array(404,400,500))` in all your requests, since that is hiding any potential problems.  400-level errors relate to client-side issues (syntax errors, etc), while 500 errors are server-related.  You should generally not be ignoring those unless you have a good reason to.

Finally, it looks like the function_score is not in the right place in your query.  It should be part of the `query` itself, not a top-level parameter.

**Comment by mrverak** [comment]
I getting this exception now. can you please what is this?
`Elasticsearch\Common\Exceptions\BadRequest400Exception
 {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"no handler for type [keyword] declared on field [raw]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [programs]: no handler for type [keyword] declared on field [raw]","caused_by":{"type":"mapper_parsing_exception","reason":"no handler for type [keyword] declared on field [raw]"}},"status":400}
`

**Here is my mapping for particular field:**

```
'city_name' => array(
				'type' => 'string',
				'fields' => array(
					'raw' => array(
						'type' => 'keyword',
						'index' => 'not_analyzed'
					)
				)
			)

```

**Comment by mrverak** [comment]
And more Critical is 
`{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer [not_analyzed] not found for field [institution]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [programs]: analyzer [not_analyzed] not found for field [institution]","caused_by":{"type":"mapper_parsing_exception","reason":"analyzer [not_analyzed] not found for field [institution]"}},"status":400}`

**Comment by polyfractal** [comment]
I'm going to close this and suggest you take the questions to the forums, sorry :(  I just don't have the bandwidth to do extensive troubleshooting of general Elasticsearch problems... we try to keep the issues here mainly about the PHP client.

I'm guessing that you're having problems updating the mapping because fields become immutable after creation.  You cannot change the mapping of an existing field. Instead, you'll have to create a new index with the mapping you want and reindex into it from your old index.

Goodluck!
