### ISSUE TITLE
deleteByQuery method status of art

### ISSUE THREAD

**Issue by orange-square** [elastic/elasticsearch-php#623]
### Summary of problem or feature request
Multiple document deletion unfeatured.

### Code snippet of problem

```php
<?php
    /**
     * @deprecated
     * $params[''] @todo finish the rest of these params
```
Can I use it?
Is going to be deprecated or completed?
How to configure routing parameters?
If going to be deprecated what's the alternative to perform a bulk delete?

### System details

- Debian linux
- PHP 5.6
- ES-PHP 2.3
- Elasticsearch 5.4

**Comment by polyfractal** [comment]
You should upgrade to a newer version of Elasticsearch-PHP (the 5.x branch).  It is no longer deprecated: https://github.com/elastic/elasticsearch-php/blob/5.0/src/Elasticsearch/Client.php#L270

DBQ was originally deprecated and removed from Elasticsearch itself, then they brought it back with a new implementation.  So in ES-PHP it was marked as deprecated and then un-deprecated in later versions. :)

That said, you should try to keep your ES-PHP major version matching elasticsearch's major version.  E.g. ES-PHP 2.x goes with Elasticsearch 2.x, ES-PHP 5.x goes with Elasticearch 5.x, etc :)

**Comment by orange-square** [comment]
OK actually I cannot move to an higher version due to project dependencies.
Said this would not be a good idea to maintain elder versions readibility?

**Comment by polyfractal** [comment]
I'm afraid you're a bit stuck then.  After DBQ was re-introduced into Elasticsearch, the API's endpoint changed a little. It went from: `"/$index/$type/_query"` to: `"/{$this->index}/{$this->type}/_delete_by_query"`

> Said this would not be a good idea to maintain elder versions readibility?

Starting with Elasticsearch 2.0, the whole ecosystem has moved to unified releases.  That means that if you are on Elasticsearch 2.0, your clients, logstash, kibana, beats, etc should all be on 2.x as well.  That helps keep version compatibility across the whole ecosystem.

We can't go back and change ES-PHP 2.x to support ES 5.x, because it would break compatibility.  DBQ is a good example, it changed in 5.x, meaning you need to use ES-PHP 5.x to access the new API.

Sorry :(

**Comment by orange-square** [comment]
Sorry I didn't get it was removed in elastic search 2.0
Because the code in the client says "to complete" (regarding parameters documentation), then it was deprecated, but heredoc is a bit confusing.
I was propousing to correct and complete heredoc, keeping it deprecated.

**Comment by polyfractal** [comment]
Oh gotcha, i misunderstood :)

++ I'll make some changes to that comment to make it clearer what happened. I'll find the version numbers of Elasticsearch that were affected too, to help make it clear.

**Comment by orange-square** [comment]
Thanks!

**Comment by ezimuel** [comment]
Outdated issue.
