### ISSUE TITLE
How to set ttl?

### ISSUE THREAD

**Issue by josecybertill** [elastic/elasticsearch-php#624]
This is a question, rather than an issue but I could not find anywhere in the documentation, how do I set ttl (time to live) for my documents? Also, I would like to use query and request cache, more details in the snippet (I set it to 1 minute for the example).

### Snippet

```php
<?php
require 'vendor/autoload.php';

use Elasticsearch\ClientBuilder;

$client = Elasticsearch\ClientBuilder::create()->build();

$params = [
    'index' => 'my_index',
    'body' => [
        'settings' => [
            'ttl' => '14M',
            'query_cache' => true,
            'request_cache' => true,
            'number_of_shards' => 1,
            'number_of_replicas' => 0
        ]
    ]
];

$client->indices()->create($params);
```

### System details

- Operating System: Debian
- PHP Version: 5.4
- ES-PHP client version: 2.0
- Elasticsearch version: 2.0

**Comment by polyfractal** [comment]
Your syntax is a little off.  You need to set `_ttl: enabled` in the mapping of your index, not the settings.  See the docs here:  https://www.elastic.co/guide/en/elasticsearch/reference/2.0/mapping-ttl-field.html#_default_ttl

In PHP, that'd be:

```php
$client = Elasticsearch\ClientBuilder::create()->build();

$params = [
    'index' => 'my_index',
    'body' => [
        'mappings' => [
          'my_type' => [
            'properties' => [
              'some_field' => [ 'type' => 'string'],
            ],
            'ttl' => [
              'enabled' => true,
              'default' => '14M'
            ]
        ],
        'settings' => [
            'number_of_shards' => 1,
            'number_of_replicas' => 0
        ]
    ]
];

$client->indices()->create($params);
```

Both the query_cache (renamed to 'node query cache' in 2.x) and request_cache (renamed to 'shard request cache' in 2.x) are static configs that need to be set in your `elasticsearch.yml`:

https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-cache.html
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/shard-request-cache.html#_cache_settings

Do note that `_ttl` is deprecated in 2.x and removed entirely in 5.0+.  I wouldn't build any functionality on top of it to be honest, since it'll keep you from upgrading.

**Comment by josecybertill** [comment]
Thank you very much @polyfractal

**Comment by polyfractal** [comment]
Happy to help! :)
