### ISSUE TITLE
[v2.2.1] Invalid response code when data node is not available

### ISSUE THREAD

**Issue by dnahrebecki** [elastic/elasticsearch-php#632]
I run locally cluster with 2 nodes: master + data. For testing purpose, let's run only master node and data node let's keep dead.
Now, I'm trying to send following request:

```json
{
   "http_method":"HEAD",
   "scheme":"http",
   "uri":"xxx",
   "body":null,
   "headers":{
      "host":[
         "127.0.0.1:9200"
      ]
   },
   "client":{
      "verbose":true
   }
}
```

At this point everything is ok, connection is marked as alive, response is HTTP 200. But when it comes to POST some data to index, eg.
```json
{
   "http_method":"POST",
   "scheme":"http",
   "uri":"xxx/_bulk",
   "body":"{\"delete\":{\"_type\":\"xxx\",\"_id\":64}}\n",
   "headers":{
      "host":[
         "127.0.0.1:9200"
      ]
   }
}
```
Such request will first wait for 60s (default timeout) and then returns following response:

```json
{
   "transfer_stats":{
      "url":"xxx/_bulk",
      "content_type":"application\/json; charset=UTF-8",
      "http_code":200,
      "header_size":87,
      "request_size":136,
      "filetime":-1,
      "ssl_verify_result":0,
      "redirect_count":0,
      "total_time":60.001781,
      "namelookup_time":2.9e-5,
      "connect_time":2.9e-5,
      "pretransfer_time":5.8e-5,
      "size_upload":46,
      "size_download":346,
      "speed_download":5,
      "speed_upload":0,
      "download_content_length":346,
      "upload_content_length":46,
      "starttransfer_time":60.001673,
      "redirect_time":0,
      "redirect_url":"",
      "primary_ip":"127.0.0.1",
      "certinfo":[

      ],
      "primary_port":9200,
      "local_ip":"127.0.0.1",
      "local_port":52664,
      "error":"",
      "errno":0
   },
   "curl":{
      "error":"",
      "errno":0
   },
   "effective_url":"http:\/\/127.0.0.1:9200\/xxx\/_bulk",
   "headers":{
      "Content-Type":[
         "application\/json; charset=UTF-8"
      ],
      "Content-Length":[
         "346"
      ]
   },
   "version":"1.1",
   "status":200,
   "reason":"OK",
   "body":{
      "took":60000,
      "errors":true,
      "items":[
         {
            "delete":{
               "_index":"xxx",
               "_type":"xxx",
               "_id":"64",
               "status":503,
               "error":{
                  "type":"unavailable_shards_exception",
                  "reason":"[xxx][4] primary shard is not active Timeout: [1m], request: [BulkShardRequest to [xxx] containing [1] requests]"
               }
            }
         }
      ]
   }
}
```

So the questions are: 
* why when (let's say internal) response is 503, the Client receive HTTP 200 with response like above (see "status":200)? Application thinks that request was successfuly processed, marks connection as alive etc. but actually it's not. 
* How can I change default timeout? https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php#L15 as far as I see it's not accessible by any setter or via constructor's args.

### System details

- Operating System: ubuntu 16
- PHP Version: 7.0
- ES-PHP client version: v2.2.1
- Elasticsearch version: v2.4.1

**Comment by polyfractal** [comment]
> why when (let's say internal) response is 503, the Client receive HTTP 200 with response like above (see "status":200)? Application thinks that request was successfuly processed, marks connection as alive etc. but actually it's not.

See: https://github.com/elastic/elasticsearch/issues/25156#issuecomment-307429991

Basically, the status code represents the status of the coordinating node (the node that received the request).  In this case, the coordinating node successfully parsed and executed the Bulk request. The actions to be executed inside the bulk were transferred (potentially) to other nodes and processed in the shards, where they failed.  The error responses were collected and sent back to the client.

So while the actions failed, the bulk itself was "successful" because there was no parse error, no bad syntax, no problems on the coordinating node, etc.  So the request's status code was 200.

> How can I change default timeout? https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php#L15 as far as I see it's not accessible by any setter or via constructor's args.

Do you want to change the ping timeout, or the request timeout?  Ping timeout is just for connection pool pinging to determine liveness when requests aren't being executed.

If you want to control the timeout of the bulk request (or any request), you can set the timeout on a per-request basis: https://www.elastic.co/guide/en/elasticsearch/client/php-api/2.0/_per_request_configuration.html#_curl_timeouts

**Comment by dnahrebecki** [comment]
@polyfractal thanks for the answer. all clear for me now.

**Comment by polyfractal** [comment]
:+1: Happy to help.  It is definitely a confusing situation, you aren't the only one that's bumped into that particular situation and been confused :)
