### ISSUE TITLE
[v2.2.1] Exists check marks connection as dead

### ISSUE THREAD

**Issue by aivus** [elastic/elasticsearch-php#636]
### Summary of problem or feature request

I'm using `StaticConnectionPool` as connection pool.
Library marks connection as dead in case of `indices()->exists(['index' => 'non_existing_index])` returns false.

It happens due to `Transport::performRequest` marks connections as dead via `$this->connectionPool->scheduleCheck();` in promise.

### Code snippet of problem
```
        /** @var Connection $connection */
        $connection = $this->esClient->transport->getConnection();
        $connection->markDead();
        $this->assertFalse($this->esClient->indices()->exists(['index' => 'not_existing_index']));
        // It's actually should be true, but elasticsearch-php library mark connection as dead
        $this->assertFalse($connection->isAlive());
```

### System details

- Operating System: macOS 10.12.6
- PHP Version: 7.1.8
- ES-PHP client version: v2.2.1
- Elasticsearch version: 2.4.4

**Comment by polyfractal** [comment]
I'm a bit confused about your scenario, can you explain some more?  Are you having a problem with normal usage of the client?  Because your snippet is using a lot of internal APIs meant to be used only by the client itself.

A few notes:

`$this->esClient->transport->getConnection();` is an internal API.  It retrieves the next connection and causes the connection pool to advance.  Which means that if you have more than one connection in the pool, your `exists` call will internally also invoked `getConnection()`, advance the connection pool and cause the request to be invoked on a different connection than the one you just grabbed in your code.

Secondly, the pool marks all nodes as dead to start (https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticConnectionPool.php#L28), so it's possible you are seeing a "dead" node simply because it hasn't been used yet.

**Comment by polyfractal** [comment]
Instead, you could use `getLastConnection()` on the transport to check, although I'm still curious what the ulterior motive is :)

```php
$this->assertFalse($this->esClient->indices()->exists(['index' => 'not_existing_index']));

/** @var Connection $connection */
$connection = $this->esClient->transport->getLastConnection();
$this->assertTrue($connection->isAlive());
```

Do note that `exists` uses `BooleanRequestWrapper` (https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Namespaces/BooleanRequestWrapper.php#L30), which will return false for A) not existing B) Missing 404 or C) Routing exception. All other exceptions will be thrown as an actual exception, and no value is returned.

**Comment by aivus** [comment]
I'm creating own connection poll and It's a part of my integration tests
actually.

404 exception causes onFailure callback of the promise as I mentioned
above. And this callback marks all connections as dead by calling
scheduleCheck

**Comment by polyfractal** [comment]
Ah yep, I see what you mean.  The comments seem to suggest that 4xx errors went through the success handler, although I'm not sure why that would've been the case... this code hasn't been touched in a long time :)

I can make a small tweak to ignore checks on 4xx level errors, which I think is correct and bwc.  Need to run/write some tests first.

Thanks for the bug report!

**Comment by polyfractal** [comment]
Should be fixed in all branches.  I'll tag a 2.x release in a few minutes after tests have a chance to spin.

As an aside, you should probably upgrade soon.  We follow Elasticsearch in terms of EOL and maintenance, and starting with 6.0 the 2.x branch will no longer be maintained: https://www.elastic.co/support/eol

**Comment by meyerbaptiste** [comment]
@polyfractal your fix is not correct and introduces another bug.

```php
function ($response) {
    // Ignore 400 level errors, as that means the server responded just fine
    if (!(isset($response['code']) && $response['code'] >=400 && $response['code'] < 500)) {
        // Otherwise schedule a check
        $this->connectionPool->scheduleCheck();
    }
});
```

In fact, the `$response` is rarely an exception that implements the `ArrayAccess` interface (never for the exceptions of this lib). So the `isset($response['code'])` test throws an `Error` exception (e.g. `Cannot use object of type Elasticsearch\Common\Exceptions\Missing404Exception as array` in your integration test) which is caught and silenced since https://github.com/reactphp/promise/pull/51.
