### ISSUE TITLE
High performance cost just connecting

### ISSUE THREAD

**Issue by floggle** [elastic/elasticsearch-php#640]
PHP: 5.6.15 (with curl 7.42.1
es-php: 5.0.0
Apache: 2.4.17.0
ES: 5.5.0 (one node)
Everything is running on a quad core localhost dev machine. Windows 7 x64.

I've been doing some JMeter testing and it seems I'm getting some really poor performance out of the library, specifically at connection time.
* If I make my search query directly to ES, I get a max throughput of about 400 requests per second. Great.
* My PHP page *before* it connects to ES (an (exit() on the line above)) gives a throughput of about 600/s
* If I exit() the script right after connecting to ES, my throughput plunges to 180/s. Just connecting, not searching! My CPU is at maxed out with a split of 90% to Apache, and 5% to ES.
* If I then throw in my query (and exit() on the next line), I'm down to about 100/s. The CPU split now is 70% Apache, 30% ES.

As you can see, most of the performance hit seems to come from just connecting from PHP to ES.

This is my connecting PHP:

```
# exit();
# Connects to localhost:9200 by default
$es_conn = Elasticsearch\ClientBuilder::create()
	# Set the hostname/port of the ES Server
	->setHosts(array(ES_HOSTS))
	# Actual connect
	->build();
# exit();

# Query to ES
$response = $es_conn->search($params);
# exit();
```

I appreciate there should be some performance cost to connecting ES and PHP together, but that seems really high, and it's almost all on the PHP side.

**Comment by polyfractal** [comment]
I haven't run benchmarks for a while, but the slowdown is almost certainly class loading costs.  

The default connection pool for ES-PHP is the [StaticNoPingConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_connection_pool.html#_staticnopingconnectionpool_default), which doesn't do any kind of initialization on startup (e.g. nothing "connects" until the first actual request is sent).  The builder and client initialization is really just building the object and that's it.

If your benchmark is basically load script -> initialize client -> exit script -> repeat, you're paying a heavy overhead with Composer's autoloader / class loading.  Basically, composer loads classes on-demand, so when the client is initialized it has to fetch a number of classes off of disk and load them into memory.  The client is kept purposefully compact, and uses a relatively lightweight transport library (RingPHP) for this very reason, but there are still a few classes that have to be loaded.

Composer [has this to say about the autoloader](https://getcomposer.org/doc/articles/autoloader-optimization.md):

> By default, the Composer autoloader runs relatively fast. However, due to the way PSR-4 and PSR-0 autoloading rules are set up, it needs to check the filesystem before resolving a classname conclusively. This slows things down quite a bit, but it is convenient in development environments because when you add a new class it can immediately be discovered/used without having to rebuild the autoloader configuration.

The last time I benchmarked it, autoloader costs were around 3-6ms.  Which is 160-300 "script reloads per second", not far off from your numbers.

There are a few ways to help here:

1. Optimize your autoloader using one of the techniques listed here: https://getcomposer.org/doc/articles/autoloader-optimization.md.  These techniques generate flat maps that are used for lookups, rather than parsing the class name and finding the class on disk recursively
2. [Enable the Opcache](https://stackoverflow.com/a/17304671) if you haven't already.  The opcache will cache the class's byte code rather than re-parsing each time the PHP script is loaded
3. Use longer-lived clients.  E.g. there is an overhead to the client initialization, regardless of how you optimize it.  More realistic benchmarks initialize the client and perform a number of operations before tearing the script down.  If your real production environment really does initialize the client, execute a single search and quit... you might want to consider doing a manual curl call instead of using the client.  PHP isn't known for being speedy, and there are real costs to using *any* additional library.  Which unfortunately means that the client can be too slow for ultra-low latency scripts that use a single request.
4. Upgrade to PHP7, which has a number of performance improvements over 5.x

Hope this helps!
