### ISSUE TITLE
version conflict, current version updateByQuery

### ISSUE THREAD

**Issue by tuananhzippy** [elastic/elasticsearch-php#650]
`"index":"mse","type":"keywords","id":"99228","cause":{"type":"version_conflict_engine_exception","reason":"[keywords][99228]: version conflict, current version [3] is different than the one provided [2]","index_uuid":"4A0kdZLYQ5qieZAYqzn3Aw","shard":"0","index":"mse"},"status":409},`

**Comment by polyfractal** [comment]
Sorry for delay, was on holiday and then a week-long work trip.

This sounds like you provided a version in your update, but the version of the document has been incremented past the provided version.  The Version conflict exception is just telling you that the update was not valid because the version is wrong.

It's not an error with the client, rather an exception to let you know the consistency guarantees you specified (the version) were not able to be met.

**Comment by mjames21** [comment]
Adding ?conflicts=proceed after _update_by_query solve the issue for me

POST twitter/_update_by_query?conflicts=proceed
{
  "script": {
    "source": "ctx._source.likes++",
    "lang": "painless"
  },
  "query": {
    "term": {
      "user": "kimchy"
    }
  }
}
