### ISSUE TITLE
How to exclude index type in elastic search version 5.6

### ISSUE THREAD

**Issue by Akshayprmar** [elastic/elasticsearch-php#654]
### Summary of problem or feature request
Hi ,
i have created one index and multiple type in there.
such as a index name:index1
and index1 type:
index1_type1
index1_type2
index1_type3
.
.
.
index1_type135
so i want to exclude data from index1_type2 in all dataset.

so i have tried below query in elasticsearch but it's giving some error.
**query**
GET /index1/_search
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
"filtered": {
    "not": {
      "filter": {
        "type": {
          "value": "index1_type2"
        }
      }
    }
  }
    }
  }
}
**error**
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "[bool] query does not support [filtered]",
        "line": 6,
        "col": 13
      }
    ],
    "type": "parsing_exception",
    "reason": "[bool] query does not support [filtered]",
    "line": 6,
    "col": 13
  },
  "status": 400
}

**Comment by polyfractal** [comment]
This looks like a generic Elasticsearch question, not relating to the query.  Please take questions like this to the [Elasticsearch Discuss Forums](https://discuss.elastic.co/c/elasticsearch), since they are better suited for that sort of question.

Your query is failing because the boolean query doesn't have any parameter called `"filtered"`.  There is a `"filter"` param which you can use.  The `"not"` query doesn't exist anymore though, so you should probably revisit the entire query and update it for 5.x (it looks like you are using old syntax).  Docs are here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html
