### ISSUE TITLE
Unable to use reverse_nested aggregation without a path parameter

### ISSUE THREAD

**Issue by jsnod** [elastic/elasticsearch-php#660]
### Summary of problem

When using the `reverse_nested` aggregation, the `path` parameter is optional, but if you don't include it, the query fails with:

```Expected [START_OBJECT] under [reverse_nested], but got a [START_ARRAY] in [accounts]```

According to https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-aggregations-bucket-reverse-nested-aggregation.html the default for the `path` parameter is empty, or  ```"reverse_nested": {}``` in JSON notation.

### Code snippet of problem

```php
$nestedAgg = [
  'nested' => ['path' => 'second_level'],
  'aggs' => [
    'secondLevelFilter' => [
      'filter' => [...],
      'aggs' => [
        'secondLevelHistogram' => [
          'date_histogram' => ['field' => 'second_level.time', 'interval' => 'hour'],
          'aggs' => [
            'backToRoot' => [
              'reverse_nested' => [],
              'aggs' => [...]
            ]
          ]
        ]
      ]
    ]
  ]
];
```

The workaround I found is to explicitly cast the empty array to an object, like so:
```php
'reverse_nested' => (object)[]
```
Maybe that is all that is expected, but perhaps there should be some documentation on this oddity if so.  Or ideally, the library could automatically cast empty arrays to objects in the background?

### System details

- Operating System: CentOS 7.3
- PHP Version: 5.6.25
- ES-PHP client version: 5.3.0
- Elasticsearch version: 2.4.5

**Comment by polyfractal** [comment]
Yep, it's a crappy situation unfortunately.  There's not a good solution for the client, since Elasticsearch uses empty objects and empty arrays in various places.  Since both are used, we can't automatically convert one to the other... something will always be broken :(

There's a section in the docs talking about this ([Dealing with JSON Arrays and Objects in PHP
e](https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/php_json_objects.html)) but perhaps it should be named something a bit more obvious.  In the docs I recommended using `stdClass`, but casting to `object` works just fine as well.

Sorry you ran into this, open to suggestions... but every time I revisit this it doesn't seem like there is a good solution.  What we really need is a definitive body specification from Elasticsearch that details all requests, then the client could validate each body in context and check for arrays/objects.  But until then, we can't validate anything and it's up to the user :(

**Comment by ezimuel** [comment]
Outdated issue.
