### ISSUE TITLE
How to figure out what shard a document would goto?

### ISSUE THREAD

**Issue by morphers82** [elastic/elasticsearch-php#709]
I figured out that elasticsearch uses Murmur3 to figure out which shard to send a doc to: 
elasticsearch/core/src/main/java/org/elasticsearch/cluster/routing/Murmur3HashFunction.java

I am looking at trying to figure out how I can calculate what shard a doc would goto using php based on the docid and the known number of shards in its given index.

I am looking at using this code: https://github.com/lastguest/murmurhash-php/blob/master/src/lastguest/Murmur.php  to use as the algorithm in php, would this be correct?  If not, what would work?
Could this be added to the elasticsearch-php as a class of some sort?  or is there already one available?

**Comment by polyfractal** [comment]
Hey @morphers82, sorry for the delay... was on holiday :)

You're correct that ES (currently) uses Murmur3 for hashing document routing values.  But that's considered an internal implementation detail and could change in the future.  Generally, where the document is routed is also considered internal to ES and not something you can control directly.

You can, however, specify a [custom routing value](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html).  This instructs ES to hash based on the value instead of the document ID, so that you can control how documents are routed.  It still doesn't let you choose the *specific* shard, but it does make sure all values with that routing value go to the same shard.

Why do you need to know which specific shard a document is routed to?  Perhaps I can help with the underlying issue you're trying to solve?

**Comment by morphers82** [comment]
thx for the reply.
I lost a few shards due to some nvme failures and I don't want to reindex the entire dataset.  I currently figured out how to ask elastic api which doc Id gets routed to what shard, but this requires gathering all data for 110million doc id's, and have to do it for any index with a differing shard count (not sure yet if it changes even amongst same shard sized indices)  so id prefer being able to just use php to figure it out without all the 110million request to the cluster for each doc/shard combination for each different shard count.

**Comment by morphers82** [comment]
I am using the search_shards feature and after comparing millions of ids, i can safely assume that the routing only depends on shard size, so i only have to recalculate based on the number of shards for the same type of ids.  still would like to not have to do this.

**Comment by polyfractal** [comment]
Yeah, routing is determined solely by the number of primary shards and the "routing value" (default to doc ID, or whatever custom value is provided):

`shard_num = hash(_routing) % num_primary_shards`

I don't think this is functionality we can put into the client though... there are too many edge-cases.  Predominantly, it's really an internal implementation detail that can change at any time (there was such a change some time ago in 2.x iirc).  There are also additional complications like user-defined routing, or if the user has used the shrink API.  And in the future shard layout will become even more flexible allowing the user to grow shard sizes.

I think that'd be too trappy of an API to implement in the client, and could easily make situations worse (duplicate documents routed to different shards, etc).

Since you have the original data, you could probably get by with just spamming updates.  If the documents are identical, [updates are no-ops](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_detecting_noop_updates) so you only pay the network overhead cost.  If you do bulk batches of updates the network cost will amortized and you're really only paying the cost to fetch each document.

It should be faster than Reindexing since most of the operations will be no-ops.

Or you could scroll your way through the data and index any documents that appear to be missing.

Or you could go the murmur3 route like you mentioned, although you'll just have to be careful everything is working as intended so you don't index duplicates.

But since it's only 100m docs and you have NVMe's, I think I'd just blast through all of them with updates.  Should go reasonably quickly.

**Comment by ezimuel** [comment]
Outdated issue.
