### ISSUE TITLE
[Question] Search with min_score

### ISSUE THREAD

**Issue by victor-gabou** [elastic/elasticsearch-php#723]
Hello,

I'm currently working on a geolocated search.
The query use the multi_match with a geo_distance filter and is sort by distance.
To refine the searches I find [min_score](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-min-score.html) that works perfectly.

In the client, the min_score seems to only be enable for the count method.
I was wondering if there is a specific reason?

Thanks,
Victor Gabou

**Comment by polyfractal** [comment]
Search accepts `min_score` too... but it's part of the body parameter in search, whereas the Count API doesn't have a body so it needs to be part of the URL query string.  Query string params are whitelisted but body params are not validated at all, which is why you saw `min_score` only for count.

You can do something like:

```php
$client->search([
  'index' => 'foo',
  'body' => [
    'min_score' => 123,
    'query' => [ ... ]
  ]
]);

**Comment by victor-gabou** [comment]
Oh right!

Actually I was using the good way but with a too small value to see changes --"

Thanks!
