### ISSUE TITLE
Bulking documents to ES using concurrent requests 

### ISSUE THREAD

**Issue by xserrat** [elastic/elasticsearch-php#724]
### Summary of problem or feature request

I'm trying to make a bulk of all my documents but making multiple requests to ES at the same time. I've seen how to make requests with the async mode through [Future mode](https://www.elastic.co/guide/en/elasticsearch/client/php-api/5.0/_future_mode.html#_future_mode) but it still waiting the response and doesn't make multiple requests in parallel...

### System details

- Operating System: `Linux  2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`
- PHP Version: `7.1.6`
- ES-PHP client version: `5.1`
- Elasticsearch version: `5.1.2`

Thank you so much!

**Comment by polyfractal** [comment]
Can you post your code?  Can you explain how you know they aren't being executed correctly?

The async feature of the client is fairly limited, due to how PHP works.  Essentially, it queues up requests and submits them to curl's multi-handler interface, which executes the entire set of requests in parallel.  However, due to the nature of PHP and the interface between curl and PHP, the entire set of requests have to complete before curl can return the responses to PHP-land.

So this means the latency of any response is bounded by the slowest response in the set of requests.  99 requests that take 1ms and 1 request that takes 1000ms will force all requests in that batch to take 1000ms to return.

The related detail is that response futures only resolve once the batch completes, not when the individual request is done.  So this can make it appear that the requests aren't executing in parallel, since they only resolve when the batch completes.

Lastly, if you just want to bulk index documents quickly, you don't need future mode.  You can just use the bulk indexing method.  The future execution is mainly if you have a bunch of unrelated single-API requests that need to execute and don't depend on ordering.  Firing them off in an async batch can save some overall execution time since curl can process them in parallel.

**Comment by xserrat** [comment]
Sorry @polyfractal I haven't explained properly.

As you said, I just want to bulk index documents quickly and to do that, currently I retrieve information about some documents using a MySQL query (every 20.000 documents). Then each document is added to an array of documents and when I have about 5000 I make a request to elastic using the bulk endpoint. I show you an example:

```php

$mysql_elements_to_index = $this->queryToMySql($offset = 0, $limit = 20000);

$body = [];

foreach ( $mysql_elements_to_index as $index => $current_element ) {
       $body[] = [
             // Fields for every document (_index, _id, _type)
       ];
       $body[] = $current_element; //This goes in a separate position

       if ($index % 5000 == 0) {
             $this->makeRequestToElastic($body); // This method calls the bulk endpoint
             $body = [];
       }
}

```
My goal is to improve the speed of every request to elastic using async requests. So when I tried to find the way I saw the Future Mode and the use of the handler named `Multihandler`. But with this way I've seen that the time to execute all requests will be the same because you need to iterate for each future returned in order to call the method `wait` to make effective the request.

So the way we've find to make the whole bulk as soon as possible is the use of an script which launches multiple bulk scripts. 

What do you think about that?

Thanks so much for your time.

**Comment by xserrat** [comment]
Hi @polyfractal ,

Finally, we've refactored the code in order to generate isolated chunks to bulk the documents independently of each other. It means that there are many scripts responsible for indexing a chunk of documents and each one is executed by a worker which is listening messages of a queue.

Using this technique we've achieved our goal of bulking 450.000 documents in parallel in 10 minutes.
