### ISSUE TITLE
remaining timeout of 999 too small to resolve via SIGALRM method (No alive nodes found in your cluster)

### ISSUE THREAD

**Issue by marcing** [elastic/elasticsearch-php#742]
I am getting errors like this on my cluster:
Elasticsearch\Common\Exceptions\NoNodesAvailableException
elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51

The ping in nextConnection fails for unknown reason and the index request is not performed, which results in irreversible data loss. Error message from lastRequestInfo:

```
            "error": "remaining timeout of 999 too small to resolve via SIGALRM method",
            "errno": 28
```
Rate of erroneous connections is 0,000625%, but since it's used for payment notifications every record lost is unacceptable.

### Code snippet of problem
```php
    /** @var float  */
    private $pingTimeout = 1;    //TODO expose this

    public function nextConnection($force = false)
    {
        $skipped = array();

        $total = count($this->connections);
        while ($total--) {
            /** @var Connection $connection */
            $connection = $this->selector->select($this->connections);
            if ($connection->isAlive() === true) {
                return $connection;
            }

            if ($this->readyToRevive($connection) === true) {
                if ($connection->ping() === true) {
                    return $connection;
                }
            } else {
                $skipped[] = $connection;
            }
        }

        // All "alive" nodes failed, force pings on "dead" nodes
        foreach ($skipped as $connection) {
            if ($connection->ping() === true) {
                return $connection;
            }
        }

        throw new NoNodesAvailableException("No alive nodes found in your cluster");
    }
```

```
    [lastRequestInfo] => {
    "request": {
        "http_method": "HEAD",
        "scheme": "http",
        "uri": "\/",
        "body": null,
        "headers": {
            "Host": [
                "xx.xx.xx.101:9200"
            ],
            "Content-Type": [
                "application\/json"
            ],
            "Accept": [
                "application\/json"
            ]
        },
        "client": {
            "curl": {
                "156": 300, // CURLOPT_CONNECTTIMEOUT_MS = 300
                "13": 1 // ping 
            }
        }
    },
    "response": {
        "transfer_stats": {
            "url": "http:\/\/xx.xx.xx.101:9200\/",
            "content_type": null,
            "http_code": 0,
            "header_size": 0,
            "request_size": 0,
            "filetime": -1,
            "ssl_verify_result": 0,
            "redirect_count": 0,
            "total_time": 0,
            "namelookup_time": 0,
            "connect_time": 0,
            "pretransfer_time": 0,
            "size_upload": 0,
            "size_download": 0,
            "speed_download": 0,
            "speed_upload": 0,
            "download_content_length": -1,
            "upload_content_length": -1,
            "starttransfer_time": 0,
            "redirect_time": 0,
            "redirect_url": "",
            "primary_ip": "",
            "certinfo": [],
            "primary_port": 0,
            "local_ip": "",
            "local_port": 0,
            "error": "remaining timeout of 999 too small to resolve via SIGALRM method",
            "errno": 28
        },
        "curl": {
            "error": "remaining timeout of 999 too small to resolve via SIGALRM method",
            "errno": 28
        },
        "effective_url": "http:\/\/xx.xx.xx.101:9200\/",
        "status": null,
        "reason": null,
        "body": null,
        "headers": [],
        "error": {}
    }

### System details

- Linux
- PHP 7.1.13
- ES-PHP client version: 5.3.2
- Elasticsearch version: 5.6.5

Any ideas? The error states that 1s limit is not enough, but why? Cluster is really fast and other services are never getting a even a 1s timeout.

Best regards,
Marcin

**Comment by polyfractal** [comment]
It appears to be a limitation of curl:

https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT_MS.html

> If libcurl is built to use the standard system name resolver, that portion of the transfer will still use full-second resolution for timeouts with a minimum timeout allowed of one second.
>
>In unix-like systems, this might cause signals to be used unless CURLOPT_NOSIGNAL is set. 

So it appears the value you set (300ms) isn't valid, because unix signals don't have that resolution.  You may need to build a different version of curl that allows async domain lookups, or disable the signals, or something else.  I'm afraid this is a bit outside my knowledge.

But it appears to be an issue with curl, not the client itself.

**Comment by marcing** [comment]
Dear polyfracal,

I wish you did not close it that soon.
I tried also 1000 and 3000ms with no effect, which means it is not the reason.

What if you add an option to increase ping timeout?

Thank you,
Marcin

**Comment by polyfractal** [comment]
The issue isn't pinging, since you're using the [`StaticNoPingConnectionPool`](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php#L10) as seen in the exception message.  That pool assumes that all nodes are alive and will never ping them.

The code snippet you listed is from a different pool, the [`StaticPingConnectionPool`](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/ConnectionPool/StaticConnectionPool.php#L10)

Regardless, even if the ping timeout of `1` was being used, that value is converted appropriately by RingPHP [depending on what constants are available](https://github.com/guzzle/RingPHP/blob/master/src/Client/CurlFactory.php#L421) :

```php
if (defined('CURLOPT_TIMEOUT_MS')) {
  $options[CURLOPT_TIMEOUT_MS] = $value * 1000;
} else {
  $options[CURLOPT_TIMEOUT] = $value;
}
```

So if you're on an older curl, `CURLOPT_TIMEOUT` will be set with a value of `1` (second).  If you're on a newer curl, `CURLOPT_TIMEOUT_MS` will be set with the value of `1000` (ms).  If you also set `CURLOPT_TIMEOUT_MS` I'm not sure of the behavior on older versions, I imagine it just ignores it.  And in newer versions of curl it would overwrite the default value set by the client in newer versions.

I'd recommend trying to omit `CURLOPT_TIMEOUT_MS` entirely, perhaps your version of curl interacts with it badly. Otherwise, it may be your system resolver or the domain servers you are querying.  Perhaps try rebuilding or upgrading curl and ensure there are no strange build parameters specified.

> drop CURL all together?

PHP really only supports robust HTTP access through two mechanisms: libcurl integration and native PHP streams.  Native streams are terribly slow, so everyone uses curl.  Essentially all HTTP libraries in PHP wrap curl in some fashion.

> Other than that is is the OFFICIAL driver for PHP.
> I would expect someone to feel responsible for making it ready for production purposes and not close the ticket. The issue remains unresolved...

I'm sorry you feel this way.  I do feel responsible for the maintenance of this library, evidenced by many other (open and closed) tickets where I spend time helping users.  And this library is used by many individuals and companies in production with no catastrophic issues like the one you're encountering.  

I'm sorry you are experiencing problems, but they do not appear to be issues with the client code itself.  I may be incorrect, but from my research this very much looks like an issue with either your curl installation or your networking stack, which is why I closed the ticket.

The curl documentation explains the limitations, and the exception message is clearly being generated from curl itself, not the client:

https://github.com/curl/curl/blob/master/lib/hostip.c#L696

```c
if(timeout < 1000) {
    /* The alarm() function only provides integer second resolution, so if
       we want to wait less than one second we must bail out already now. */
    failf(data,
        "remaining timeout of %ld too small to resolve via SIGALRM method",
        timeout);
    return CURLRESOLV_TIMEDOUT;
}
```

The method that throws that error, `Curl_resolv_timeout()` is only used in two places in curl:

- For resolving the host name: https://github.com/curl/curl/blob/master/lib/url.c#L3877
- For resolving a proxy: https://github.com/curl/curl/blob/master/lib/url.c#L3898

In both cases they are dealing with domain resolution.  You should verify your system resolver is functioning correctly, and the domain servers that you are querying are available/fast enough for your needs. You should also verify that you are setting `CURLOPT_TIMEOUT_MS` correctly or remove it entirely as I suggested before.

**Comment by marcing** [comment]
Dear polyfractal,

Thank you for your effort on explaining this matter precisely. Since I tried higher timeouts, it seems like the best option is to skip connecttimeout all together.
I will try this and hopefully it helps.

Thank you!
Marcin

**Comment by marcing** [comment]
Dear polyfractal,

Thank you for your help. It helped me understand how API works.

For readers, which may face such issue in future:

Rare network delays are out of control.
Rare ES delays are out of control. 
The only working, but not entirely satisfactory solution is as follows:

1. Before any index/update/search request to ES, send a ping with connect timeout/timeout of 3s to make sure it's reachable. 
It is the only way to be sure that service (website) will load in a reasonable time when ES is not reachable.
3s seems to be enough for ping. It's not enough for ES calls other than ping (index/update/search) though.
Ping can be called as follows: 
		$client->ping([
			'client' => [
				'curl' => [
					CURLOPT_CONNECTTIMEOUT =>3,
					CURLOPT_TIMEOUT => 3,
				]
			]
		]);
2. If ping was successful, set the timeout for ES calls to 10s - in my case it is enough. If ping has failed, the ES call will exit with NoNodesAvailableException automatically without waiting (being aware of failed ping). There is no way around it in current API, but on the other hand it usually means that ES cluster is unreachable anyway.
3. Make ES call. 

Additional thoughts:

1. If we skip the ping, we have to set initial timeout of at least 10s (for HTTP). CLI of course can be longer. We risk website being unusable due to long timeouts during ES unreachability.
2. If we set lower timeout (3s) on first ES call and it fails, the consecutive call will never be executed. Good example is index/update call pair. Index fails and update never gets executed (needs _id of new document).: ES occasionally lags and CURL will return "Operation timed out after 3001 milliseconds with 0 bytes received".

Cheers
