### ISSUE TITLE
creating custom analyzer

### ISSUE THREAD

**Issue by kenny1har** [elastic/elasticsearch-php#78]
is there function for creating custom analyzer ? can provide have example ?
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html

thank you.

**Comment by DamPe88** [comment]
Hi polyfractal,
In my current project we are writing a search function using elastic search.
User search using full_name field currently we are using wildcard queries for the full_name search.
the problem is we have a document which have a name "John Doe".
this is indexed doc.
    "industry_name": "Agriculture",
     "industry_type": "Public Business",
     "full_name": "John Doe",
     "address": "Australia 1000"

The problem is If we search using "John", relevant document comes up ,but if i type "John D"
the document is not returning.

why is this happening?.
Can you help me on this?

**Comment by polyfractal** [comment]
Can you paste your full query, and the mapping for this index?  The mapping will affect how we can structure the query to get what you need back.
