### ISSUE TITLE
Can we share same connection of php-elasticsearch client to all child process ?

### ISSUE THREAD

**Issue by ashishtiwari1993** [elastic/elasticsearch-php#789]
### Sharing same connection across child process

Hi guys,

I am using this client. I have forked 20 child process for writing process in elasticsearch. Right now i have shared same connection to all child process. Should i use different connection for every child ? Also it will give any performance ? Is it a good practice to make different connection ? I also experiencing the slow writing performance. Is it going to help my any way. Below is my code. 

### Code snippet of problem

```php
$hosts = array(
                'myserver:9200',
              );
$clientBuilder = Elasticsearch\ClientBuilder::create(); 
$clientBuilder->setHosts($hosts);
$es = $clientBuilder->build();

$thread = 20;
for($i = 0; $i < $thread; $i++) {
        $pid = pcntl_fork();
        if ($pid == -1) {
                exit("Error forking...\n");
        }
        else if ($pid == 0) {
                startProcess($es);
                exit();
        }
}
```

### System details

- Operating System : centos7
- PHP Version :  7.0
- ES-PHP client version : 6
- Elasticsearch version : 6

**Comment by polyfractal** [comment]
Hey there, sorry for the delay... fell through my inbox without me noticing.

To be honest, I'm not sure if this is safe or not.  It depends if the underlying curl connections are safely accessible from forked processes. I'm not sure off the top of my head, will try to do some research.

I suspect it would be easier to simply spawn multiple instances of the PHP script, which would be functionally the same as multiple forked processes.  But they would be entirely independent and you wouldn't have to worry about shared resources.

All that said, I doubt it will help performance.  Are you having bad indexing speed?  Are you using a bulk requests?

**Comment by ezimuel** [comment]
Outdated issue. @ashishtiwari1993 if this is still an issue I'll reopen it.

**Comment by ashishtiwari1993** [comment]
@ezimuel @polyfractal  Sorry guys for late reply. Currently i am using different connection for all child process, As we do with other databases ( In case of PHP). It is working perfect. But still i have above doubt.

**Comment by ezimuel** [comment]
@ashishtiwari1993 if you are using different connections for each child process it's ok.
There's actually an experiment that you can do for sharing the same client between processes using the `ClientBuilder::multiHandler()`.

You can create the `$client` as follows:

```php
$client = ClientBuilder::create()
    ->setHandler(ClientBuilder::multiHandler())
    ->build();
```
This will use the `curl_multi_init()` instead of `curl_init()` and in this way you can share the Curl connection between process.
 **Again, this is experimental, so please test it before going in production.**
For more information, I suggest to read this nice blog post [Connection Sharing with CURL in PHP: How to re-use HTTP connections to knock 70% off REST network time](http://technosophos.com/2012/06/18/connection-sharing-curl-php-how-re-use-http-connections-knock-70-rest-network-time.html)
