### ISSUE TITLE
Index snapshot error - missing body

### ISSUE THREAD

**Issue by NatVak** [elastic/elasticsearch-php#829]
### Summary of problem or feature request

I'm trying to snapshot *one* index from ElasticSearch
my code:

### Code snippet of problem

```php
 \Elasticsearch::indices()->snapshotIndex(['index' => 'project'] );

```
I'm getting in response:

```
Elasticsearch\Common\Exceptions\BadRequest400Exception with message '{"error":{"root_cause":[{"type":"parse_exception","reason":"request body is required"}],"type":"parse_exception","reason":"request body is required"},"status":400}'
```

I tried a lot of variations , with custom, with other properties that appear in library comments, nothing works.

### System details

I'm using the wrapper laravelElastic

- Ubuntu 18.04
- PHP 7.2.10
- Elasticsearch version: 6.5.0

**Comment by polyfractal** [comment]
Oh wow, that endpoint has long since been removed from Elasticsearch.  We need to remove it from the client!  Sorry about that!

Try the `snapshot` namespace instead (corresponds to [Snapshot/Restore in ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_snapshot)).  E.g.:

```
PUT /_snapshot/my_backup/snapshot_2
{
  "indices": "index_1,index_2",
  "ignore_unavailable": true,
  "include_global_state": false
}
```
So in PHP it'd be something like:

```php
$client->snapshot()->create([
  'repository' => 'my_backup',
  'snapshot' => 'snapshot_2',
  'body' => [
    "indices" => "index_1,index_2",
    "ignore_unavailable" => true,
    "include_global_state" => false
  ]
]);
```

**Comment by ezimuel** [comment]
I removed `indices()->snapshotIndex()` from 6.5.x and 6.7.x branches. I'll release a minor for each version soon.
