### ISSUE TITLE
How to set connection pool if the es nodes is behind the load balance in PHP?

### ISSUE THREAD

**Issue by guangfanqu** [elastic/elasticsearch-php#918]
### Summary of problem or feature request

I have a elasticsearch cluster, the cluster is behind the load balance. 
And the network client to cluster node is unreachable.

If set default pool `staticNoPingConnectionPool` and if one of the nodes is dead then the client will response "No alive nodes found in your cluster" in several minutes even if the dead node had returned to normal state .

In the article "https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/connection_pool.html" I don't find the best solution. I even think the `SimpleConnectionPool` is better than other solutions.

So who can give me some suggestion?

Thanks.

### System details

- Operating System
Linux
- PHP Version
7.1.25
- ES-PHP client version
6.7.0
- Elasticsearch version
6.7.0

**Comment by ezimuel** [comment]
@guangfanqu if I got your point, the load balancer is the only service that you can connect from `elasticsearch-php`, right? If this is the case, you will have a domain name (or an IP address) for your Elasticsearch cluster managed by the load balancer. In your scenario, you don't need a connection pool from the client because it's managed by the load balancer.

In this case, I suggest to have a look at the [simpleConnectionPool](https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/connection_pool.html#_simpleconnectionpool) using only the domain service of Elasticsearch (or IP address) managed by the load balancer.

```php
$client = ClientBuilder::create()
    ->setConnectionPool('\Elasticsearch\ConnectionPool\SimpleConnectionPool', [])
    ->setHosts(['myelasticsearch.domain:9200'])
    ->build();
```

**Comment by guangfanqu** [comment]
@ezimuel 

Thanks a lot.
