### ISSUE TITLE
method Elasticsearch\Namespaces\IndicesNamespace::getAliases does not exists in v7.2.0

### ISSUE THREAD

**Issue by max-kut** [elastic/elasticsearch-php#940]
### Summary of problem or feature request
in version 7.1.* method `getAliases($params)` exists, but removed in v7.2. In docpage exists https://github.com/elastic/elasticsearch-php/blob/v7.2.0/docs/build/Elasticsearch/Namespaces/IndicesNamespace.asciidoc#Elasticsearch_Namespaces_IndicesNamespacegetAliases_getAliases

### Code snippet of problem
```php
$elasticsearch->indices()->getAliases($params->toArray());
// Call to undefined method Elasticsearch\Namespaces\IndicesNamespace::getAliases()
```
-->

### System details

- Operating System Win10
- PHP Version 7.2, 7.3
- ES-PHP client version 7.2.0
- Elasticsearch version 7.3.0

**Comment by ezimuel** [comment]
@max-kut the `IndicesNamespace::getAliases()` has been changed in favor of `IndicesNamespace::getAlias()`, this because in the API specification is `indices.get_alias`. I generate the new endpoints using a script from the API specification (see [here](https://github.com/elastic/elasticsearch/blob/v7.2.0/rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_alias.json#L2)) and I didn't notice the change. I'll add this BC break in the release note of 7.2.0. Sorry for that.

**Comment by ezimuel** [comment]
@max-kut I decided to release 7.2.1 adding a proxy function `getAliases()` to `getAlias()` to avoid BC breaks. This proxy function will be removed with 8.0. I'll release soon.

**Comment by lucasvanlierop** [comment]
https://github.com/elastic/elasticsearch-php/pull/943#issuecomment-526131060

**Comment by ezimuel** [comment]
I reopened the issue because with 7.2.1 I fixed the issue partially. I forgot to use the `$params` as optional parameter in `getAliases()` function, ops! See #946.

**Comment by ezimuel** [comment]
@lucasvanlierop I just sent #947 to fix the issue.

**Comment by ezimuel** [comment]
@lucasvanlierop I just released [7.2.2](https://github.com/elastic/elasticsearch-php/releases/tag/v7.2.2), thanks for the report.

**Comment by max-kut** [comment]
@ezimuel, @lucasvanlierop thanks for the reaction

**Comment by lucasvanlierop** [comment]
Thanks @ezimuel !
