### ISSUE TITLE
Search endpoint parameter whitelist should allow _source_include and _source_exclude

### ISSUE THREAD

**Issue by sauerbraten** [elastic/elasticsearch-php#962]
### Summary of problem or feature request

The Search endpoint parameter whitelist should allow `_source_include` and `_source_exclude` as documented: https://github.com/elastic/elasticsearch-php/blob/master/docs/build/Elasticsearch/Client.asciidoc#Elasticsearch_Clientsearch_search.

Right now, it only allows `_source_includes` (note the S at the end) and `_source_excludes`: https://github.com/elastic/elasticsearch-php/blob/f8b5d2beeeb22a5a59aabb183b5bcd7e70878d2f/src/Elasticsearch/Endpoints/Search.php#L72

The Get endpoint parameter whitelist already contains both versions: https://github.com/elastic/elasticsearch-php/blob/f8b5d2beeeb22a5a59aabb183b5bcd7e70878d2f/src/Elasticsearch/Endpoints/Get.php#L52

**Comment by ezimuel** [comment]
@sauerbraten which version of Elasticsearch are you using? The `_source_include` and `_source_exclude` parameter has been change in favor of `_source_includes` and `_source_excludes` since Elasticsearch 6.6.0 ([here](https://github.com/elastic/elasticsearch/blob/v6.6.0/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L108-L115) you can see the API specification change).

The document that you pointed out is outdated, I need to fix it. Thanks for reporting it!

**Comment by sauerbraten** [comment]
I'm using Elasticsearch 7, but was looking at https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/ElasticsearchPHP_Endpoints.html#Elasticsearch_Clientsearch_search and https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/ElasticsearchPHP_Endpoints.html#Elasticsearch_Clientget_get which both list only the deprecated variants, so I assumed it was the other way around, and 'includes' and 'excludes' were old and 'include' and 'exclude' were new.

Thanks for taking care of the docs!
