### ISSUE TITLE
putMapping : No alive nodes found in your cluster with version 7.4.0

### ISSUE THREAD

**Issue by ShyZhen** [elastic/elasticsearch-php#969]
## Environment
 - Laravel 5.8
 - ElasticSearch 7.4.2 
 - ElasticSearch-analysis-ik 7.4.2
 - ElasticSearch-PHP 7.4.0

## Error detail
First, createIndex、deleteIndex、getMappings、createDoc is OK，`$client->indices()->putMapping($params);` is error 'No alive nodes found in your cluster'.

But, i use curl to set mapping is ok. And when i add mappints in createIndex, it's ok too. 
I don't know if it's my own problem.

```
curl -XPOST http://localhost:9200/index/_mapping -H 'Content-Type:application/json' -d'
{
        "properties": {
            "content": {
                "type": "text",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_smart"
            }
        }

}'
```

-----------
## Error detail
首先，创建index、删除index、获取mappings、以及对doc的增删改查都没问题，但是当我给已有的index设置mapping的时候报错：`No alive nodes found in your cluster`.

我当时怀疑是es的问题，但是在linux上使用curl设置的时候他成功了，同时，我在创建index的时候添加mappings的设置，他也成功了，只有单独设置mapping的时候报错。我不知道这是不是我自己的问题。

**Comment by andigehle** [comment]
Can confirm this bug. I looked in the source code and found out that in the [Endpoint of putMapping](https://github.com/elastic/elasticsearch-php/blob/master/src/Elasticsearch/Endpoints/Indices/PutMapping.php#L38) in case of "index-param only" is missing a leading slash to seperate the domain and the index-param. That produces URIs like 

> https://myelastic.deMyIndex

 instead of 

> https://myelastic.de/MyIndex

====================
Fix: https://github.com/elastic/elasticsearch-php/commit/3e380b6cab9a82c52131bda67d6895aec9424d06

**Comment by chrispappas** [comment]
I was just about to submit my own comment and PR for this issue. I'm seeing exactly the same issue with the missing leading slash. Adding it back in makes it work as expected.
