### ISSUE TITLE
guzzlehttp/ringphp and guzzlehttp/streams are abandoned

### ISSUE THREAD

**Issue by reedy** [elastic/elasticsearch-php#992]
https://packagist.org/packages/guzzlehttp/ringphp is marked as abandoned, with no replacement

guzzle/ringphp depends on https://packagist.org/packages/guzzlehttp/streams which is also marked as abandoned, with no replacement

**Comment by cspshadx** [comment]
bump. got same warning from composer. any suggestions?

**Comment by ezimuel** [comment]
We are planning to refactor all the HTTP transport using PSR and/or HTTPlug and/or Symfony HttpClient (more detail here: https://github.com/elastic/elasticsearch-php/issues/990). This will be released with `elasticsearch-php 8.0`.
In the meantime, we need to find a solution for the ringphp replacement but we don't want to do double work here since we have the 8.0 plan in place. 
@cspshadx, @reedy I'll update you asap.

**Comment by orukaz** [comment]
@reedy and @ezimuel , I think the replacement is Guzzle 6 http://docs.guzzlephp.org/en/stable/handlers-and-middleware.html

For example: https://github.com/googleapis/google-api-php-client/issues/1106

> With 6th version of "guzzlehttp/guzzle" you get error:
> 
> "guzzlehttp/ringphp" dependency is not loaded by composer because
> 
> Guzzle no longer has a dependency on RingPHP. Due to the use of a middleware
system based on PSR-7, using RingPHP and it's middleware system as well adds
more complexity than the benefits it provides. All HTTP handlers that were
present in RingPHP have been modified to work directly with PSR-7 messages
and placed in the GuzzleHttp\Handler namespace. This significantly reduces
complexity in Guzzle, removes a dependency, and improves performance. RingPHP
will be maintained for Guzzle 5 support, but will no longer be a part of
Guzzle 6.

**Comment by reedy** [comment]
Bringing in all of Guzzle seems overkill... Though it seems 1.0 used to do that.

>RingPHP will be maintained for Guzzle 5 support, but will no longer be a part of Guzzle 6.

https://packagist.org/packages/guzzlehttp/guzzle says Guzzle 5 is EOL (since late October 2019 based on https://github.com/guzzle/guzzle/commit/4d71358b8f054dcb853a3ebe7cd2be08e9a0d451), so I guess that means ringphp (and streams) also no longer have any maintenance, as they're not being maintained for Guzzle 5 anymore. Presumably they just took a little while to catch up on the repo maintenance and to mark it abandoned etc

I would guess trying to backport #990 to < 8 might be a pain, considering it basically includes, 2.0, 5.0, 6.0, 6.7, 6.7, 7.0, 7.2 and 7.4...

**Comment by ezimuel** [comment]
@reedy @orukaz @cspshadx After some code review and since I'm going to refactor all the HTTP transport layer for `elasticsearch-php 8.0.0`, I decided to fork `guzzlehttp/ringphp` and `guzzlehttp/streams` and use this fork for `elasticsearch-php 7.x`. This means, I'll mantain these forks in the meanwhile. I'm preparing a PR for that.

**Comment by ezimuel** [comment]
I just sent the PR #996, please have a look thanks!
